# Development-specific Docker Compose overrides
services:
  service-backend:
    build:
      target: development
    volumes:
      - ./service.backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  app-admin:
    build:
      target: development
    volumes:
      - ./app.admin:/app/app.admin
      - ./lib.components:/app/lib.components
      - /app/app.admin/node_modules
      - /app/lib.components/node_modules

  app-client:
    build:
      target: development
    volumes:
      - ./app.client:/app/app.client
      - ./lib.components:/app/lib.components
      - /app/app.client/node_modules
      - /app/lib.components/node_modules
    environment:
      DOCKER_ENV: true

  app-rescue:
    build:
      target: development
    volumes:
      - ./app.rescue:/app/app.rescue
      - ./lib.components:/app/lib.components
      - /app/app.rescue/node_modules
      - /app/lib.components/node_modules
