# Development-specific Docker Compose overrides
services:
  service-backend:
    build:
      target: development
    volumes:
      - ./service.backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  lib-components:
    volumes:
      - ./lib.components:/app
      - /app/node_modules

  app-admin:
    build:
      target: development
    volumes:
      - ./app.admin:/app
      - /app/node_modules

  app-client:
    build:
      target: development
    volumes:
      - ./app.client:/app
      - /app/node_modules

  app-rescue:
    build:
      target: development
    volumes:
      - ./app.rescue:/app
      - /app/node_modules
