import { createTheme, createThemeContract } from '@vanilla-extract/css';

import { animations, palette, typography } from './colors';
import { highContrastPalette } from './highContrastPalette';

const colorScale = {
  '50': null,
  '100': null,
  '200': null,
  '300': null,
  '400': null,
  '500': null,
  '600': null,
  '700': null,
  '800': null,
  '900': null,
  '950': null,
};

export const vars = createThemeContract({
  mode: null,

  colors: {
    primary: { ...colorScale },
    secondary: { ...colorScale },
    neutral: { ...colorScale },
    semantic: {
      success: { ...colorScale },
      error: { ...colorScale },
      warning: { ...colorScale },
      info: { ...colorScale },
    },
    gradients: {
      primary: null,
      secondary: null,
      success: null,
      warm: null,
      cool: null,
      brand: null,
    },
    accent: {
      paw: null,
      sky: null,
      leaf: null,
      magenta: null,
    },
  },

  text: {
    primary: null,
    secondary: null,
    tertiary: null,
    quaternary: null,
    inverse: null,
    disabled: null,
    success: null,
    error: null,
    warning: null,
    info: null,
    link: null,
    linkHover: null,
  },

  background: {
    primary: null,
    secondary: null,
    tertiary: null,
    inverse: null,
    overlay: null,
    disabled: null,
    success: null,
    error: null,
    warning: null,
    info: null,
  },

  shadows: {
    none: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    inner: null,
    primary: null,
    secondary: null,
    success: null,
    error: null,
    focus: null,
    focusPrimary: null,
    focusError: null,
    focusWarning: null,
    focusSuccess: null,
  },

  border: {
    width: {
      none: null,
      thin: null,
      normal: null,
      thick: null,
      thicker: null,
    },
    radius: {
      none: null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      full: null,
    },
    color: {
      primary: null,
      secondary: null,
      tertiary: null,
      quaternary: null,
      disabled: null,
      focus: null,
      success: null,
      error: null,
      warning: null,
      info: null,
    },
  },

  spacing: {
    none: null,
    px: null,
    '0.5': null,
    '1': null,
    '1.5': null,
    '2': null,
    '2.5': null,
    '3': null,
    '3.5': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
    '9': null,
    '10': null,
    '11': null,
    '12': null,
    '14': null,
    '16': null,
    '20': null,
    '24': null,
    '28': null,
    '32': null,
    '36': null,
    '40': null,
    '44': null,
    '48': null,
    '52': null,
    '56': null,
    '60': null,
    '64': null,
    '72': null,
    '80': null,
    '96': null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    '4xl': null,
  },

  typography: {
    family: {
      sans: null,
      serif: null,
      mono: null,
      display: null,
    },
    weight: {
      thin: null,
      extralight: null,
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
    },
    size: {
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      '4xl': null,
      '5xl': null,
      '6xl': null,
      '7xl': null,
      '8xl': null,
      '9xl': null,
    },
    lineHeight: {
      none: null,
      tight: null,
      snug: null,
      normal: null,
      relaxed: null,
      loose: null,
    },
    letterSpacing: {
      tighter: null,
      tight: null,
      normal: null,
      wide: null,
      wider: null,
      widest: null,
    },
  },

  animations: {
    duration: {
      instant: null,
      fast: null,
      normal: null,
      slow: null,
      slower: null,
    },
    easing: {
      linear: null,
      easeIn: null,
      easeOut: null,
      easeInOut: null,
      bounce: null,
      elastic: null,
      smooth: null,
    },
  },

  transitions: {
    none: null,
    fast: null,
    normal: null,
    slow: null,
    slower: null,
  },

  breakpoints: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
  },

  zIndex: {
    base: null,
    docked: null,
    dropdown: null,
    sticky: null,
    banner: null,
    overlay: null,
    modal: null,
    popover: null,
    skipLink: null,
    toast: null,
    tooltip: null,
  },
});

const baseTokens = {
  typography: {
    family: {
      sans: typography.family.sans,
      serif: typography.family.serif,
      mono: typography.family.mono,
      display: typography.family.display,
    },
    weight: {
      thin: String(typography.weight.thin),
      extralight: String(typography.weight.extralight),
      light: String(typography.weight.light),
      normal: String(typography.weight.normal),
      medium: String(typography.weight.medium),
      semibold: String(typography.weight.semibold),
      bold: String(typography.weight.bold),
      extrabold: String(typography.weight.extrabold),
      black: String(typography.weight.black),
    },
    size: { ...typography.size },
    lineHeight: {
      none: String(typography.lineHeight.none),
      tight: String(typography.lineHeight.tight),
      snug: String(typography.lineHeight.snug),
      normal: String(typography.lineHeight.normal),
      relaxed: String(typography.lineHeight.relaxed),
      loose: String(typography.lineHeight.loose),
    },
    letterSpacing: { ...typography.letterSpacing },
  },

  animations: {
    duration: { ...animations.duration },
    easing: { ...animations.easing },
  },

  shadows: {
    none: 'none',
    xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    sm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    '3xl': '0 35px 60px -15px rgb(0 0 0 / 0.3)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    primary: '0 10px 25px -3px rgb(244 63 94 / 0.3), 0 4px 6px -4px rgb(244 63 94 / 0.2)',
    secondary: '0 10px 25px -3px rgb(20 184 166 / 0.3), 0 4px 6px -4px rgb(20 184 166 / 0.2)',
    success: '0 10px 25px -3px rgb(34 197 94 / 0.3), 0 4px 6px -4px rgb(34 197 94 / 0.2)',
    error: '0 10px 25px -3px rgb(239 68 68 / 0.3), 0 4px 6px -4px rgb(239 68 68 / 0.2)',
    focus: '0 0 0 3px rgb(59 130 246 / 0.5)',
    focusPrimary: '0 0 0 3px rgb(244 63 94 / 0.5)',
    focusError: '0 0 0 3px rgb(239 68 68 / 0.5)',
    focusWarning: '0 0 0 3px rgb(245 158 11 / 0.5)',
    focusSuccess: '0 0 0 3px rgb(34 197 94 / 0.5)',
  },

  spacing: {
    none: '0',
    px: '1px',
    '0.5': '0.125rem',
    '1': '0.25rem',
    '1.5': '0.375rem',
    '2': '0.5rem',
    '2.5': '0.625rem',
    '3': '0.75rem',
    '3.5': '0.875rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '11': '2.75rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '5rem',
  },

  border: {
    width: {
      none: '0',
      thin: '1px',
      normal: '2px',
      thick: '4px',
      thicker: '8px',
    },
    radius: {
      none: '0',
      xs: '0.125rem',
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      '2xl': '1rem',
      '3xl': '1.5rem',
      full: '9999px',
    },
  },

  transitions: {
    none: 'none',
    fast: '150ms cubic-bezier(0.4, 0, 0.2, 1)',
    normal: '300ms cubic-bezier(0.4, 0, 0.2, 1)',
    slow: '500ms cubic-bezier(0.4, 0, 0.2, 1)',
    slower: '700ms cubic-bezier(0.4, 0, 0.2, 1)',
  },

  breakpoints: {
    xs: '480px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },

  zIndex: {
    base: '0',
    docked: '10',
    dropdown: '1000',
    sticky: '1100',
    banner: '1200',
    overlay: '1300',
    modal: '1400',
    popover: '1500',
    skipLink: '1600',
    toast: '1700',
    tooltip: '1800',
  },

  colors: {
    primary: { ...palette.primary },
    secondary: { ...palette.secondary },
    gradients: { ...palette.gradients },
    accent: { ...palette.accent },
    semantic: {
      success: { ...palette.success },
      error: { ...palette.error },
      warning: { ...palette.warning },
      info: { ...palette.info },
    },
  },
};

export const lightThemeClass = createTheme(vars, {
  ...baseTokens,
  mode: 'light',
  colors: {
    ...baseTokens.colors,
    neutral: { ...palette.neutral },
  },
  text: {
    primary: palette.neutral[900],
    secondary: palette.neutral[700],
    tertiary: palette.neutral[600],
    quaternary: palette.neutral[500],
    inverse: palette.neutral[50],
    disabled: palette.neutral[400],
    success: palette.success[700],
    error: palette.error[700],
    warning: palette.warning[700],
    info: palette.info[700],
    link: palette.info[600],
    linkHover: palette.info[700],
  },
  background: {
    primary: palette.neutral[50],
    secondary: palette.white,
    tertiary: palette.neutral[100],
    inverse: palette.neutral[900],
    overlay: 'rgb(0 0 0 / 0.5)',
    disabled: palette.neutral[100],
    success: palette.success[50],
    error: palette.error[50],
    warning: palette.warning[50],
    info: palette.info[50],
  },
  border: {
    ...baseTokens.border,
    color: {
      primary: palette.neutral[200],
      secondary: palette.neutral[300],
      tertiary: palette.neutral[400],
      quaternary: palette.neutral[500],
      disabled: palette.neutral[200],
      focus: palette.primary[500],
      success: palette.success[300],
      error: palette.error[300],
      warning: palette.warning[300],
      info: palette.info[300],
    },
  },
  shadows: { ...baseTokens.shadows },
});

export const darkThemeClass = createTheme(vars, {
  ...baseTokens,
  mode: 'dark',
  colors: {
    ...baseTokens.colors,
    neutral: {
      '50': palette.neutral[950],
      '100': palette.neutral[900],
      '200': palette.neutral[800],
      '300': palette.neutral[700],
      '400': palette.neutral[600],
      '500': palette.neutral[500],
      '600': palette.neutral[400],
      '700': palette.neutral[300],
      '800': palette.neutral[200],
      '900': palette.neutral[100],
      '950': palette.neutral[50],
    },
  },
  text: {
    primary: palette.neutral[100],
    secondary: palette.neutral[300],
    tertiary: palette.neutral[400],
    quaternary: palette.neutral[500],
    inverse: palette.neutral[900],
    disabled: palette.neutral[600],
    success: palette.success[400],
    error: palette.error[400],
    warning: palette.warning[400],
    info: palette.info[400],
    link: palette.info[400],
    linkHover: palette.info[300],
  },
  background: {
    primary: palette.neutral[950],
    secondary: palette.neutral[900],
    tertiary: palette.neutral[800],
    inverse: palette.neutral[50],
    overlay: 'rgb(0 0 0 / 0.7)',
    disabled: palette.neutral[800],
    success: palette.success[950],
    error: palette.error[950],
    warning: palette.warning[950],
    info: palette.info[950],
  },
  border: {
    ...baseTokens.border,
    color: {
      primary: palette.neutral[800],
      secondary: palette.neutral[700],
      tertiary: palette.neutral[600],
      quaternary: palette.neutral[500],
      disabled: palette.neutral[800],
      focus: palette.primary[500],
      success: palette.success[600],
      error: palette.error[600],
      warning: palette.warning[600],
      info: palette.info[600],
    },
  },
  shadows: {
    none: 'none',
    xs: '0 1px 2px 0 rgb(0 0 0 / 0.15)',
    sm: '0 1px 3px 0 rgb(0 0 0 / 0.2), 0 1px 2px -1px rgb(0 0 0 / 0.2)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.2), 0 2px 4px -2px rgb(0 0 0 / 0.2)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.2), 0 4px 6px -4px rgb(0 0 0 / 0.2)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.2), 0 8px 10px -6px rgb(0 0 0 / 0.2)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.4)',
    '3xl': '0 35px 60px -15px rgb(0 0 0 / 0.5)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.1)',
    primary: '0 10px 25px -3px rgb(244 63 94 / 0.4), 0 4px 6px -4px rgb(244 63 94 / 0.3)',
    secondary: '0 10px 25px -3px rgb(20 184 166 / 0.4), 0 4px 6px -4px rgb(20 184 166 / 0.3)',
    success: '0 10px 25px -3px rgb(34 197 94 / 0.4), 0 4px 6px -4px rgb(34 197 94 / 0.3)',
    error: '0 10px 25px -3px rgb(239 68 68 / 0.4), 0 4px 6px -4px rgb(239 68 68 / 0.3)',
    focus: '0 0 0 3px rgb(59 130 246 / 0.2)',
    focusPrimary: '0 0 0 3px rgb(244 63 94 / 0.2)',
    focusError: '0 0 0 3px rgb(239 68 68 / 0.2)',
    focusWarning: '0 0 0 3px rgb(245 158 11 / 0.2)',
    focusSuccess: '0 0 0 3px rgb(34 197 94 / 0.2)',
  },
});

// ADS-137: High-contrast theme. White surfaces + near-black foregrounds with a
// bright-orange focus ring. All text/border tokens target >= 7:1 on the primary
// background; semantic-on-semantic-surface pairings target >= 4.5:1.
export const highContrastThemeClass = createTheme(vars, {
  ...baseTokens,
  mode: 'high-contrast',
  colors: {
    ...baseTokens.colors,
    // Override neutral with monochrome ramp so neutral-keyed styles still resolve
    // to strong-contrast values.
    neutral: {
      '50': highContrastPalette.surface.primary,
      '100': highContrastPalette.surface.tertiary,
      '200': '#E0E0E0',
      '300': '#C2C2C2',
      '400': highContrastPalette.foreground.disabled,
      '500': highContrastPalette.foreground.quaternary,
      '600': highContrastPalette.foreground.tertiary,
      '700': highContrastPalette.foreground.secondary,
      '800': highContrastPalette.foreground.primary,
      '900': highContrastPalette.foreground.primary,
      '950': highContrastPalette.foreground.primary,
    },
  },
  text: {
    primary: highContrastPalette.foreground.primary,
    secondary: highContrastPalette.foreground.secondary,
    tertiary: highContrastPalette.foreground.tertiary,
    quaternary: highContrastPalette.foreground.quaternary,
    inverse: highContrastPalette.foreground.inverse,
    disabled: highContrastPalette.foreground.disabled,
    success: highContrastPalette.semantic.success,
    error: highContrastPalette.semantic.error,
    warning: highContrastPalette.semantic.warning,
    info: highContrastPalette.semantic.info,
    link: highContrastPalette.foreground.link,
    linkHover: highContrastPalette.foreground.linkHover,
  },
  background: {
    primary: highContrastPalette.surface.primary,
    secondary: highContrastPalette.surface.secondary,
    tertiary: highContrastPalette.surface.tertiary,
    inverse: highContrastPalette.surface.inverse,
    overlay: highContrastPalette.surface.overlay,
    disabled: highContrastPalette.surface.disabled,
    success: highContrastPalette.semanticSurface.success,
    error: highContrastPalette.semanticSurface.error,
    warning: highContrastPalette.semanticSurface.warning,
    info: highContrastPalette.semanticSurface.info,
  },
  border: {
    width: {
      // Thicker default borders so component boundaries are visible without
      // relying on subtle background shifts.
      none: '0',
      thin: '2px',
      normal: '3px',
      thick: '4px',
      thicker: '8px',
    },
    radius: { ...baseTokens.border.radius },
    color: {
      primary: highContrastPalette.border.primary,
      secondary: highContrastPalette.border.secondary,
      tertiary: highContrastPalette.border.tertiary,
      quaternary: highContrastPalette.border.quaternary,
      disabled: highContrastPalette.border.disabled,
      focus: highContrastPalette.border.focus,
      success: highContrastPalette.border.success,
      error: highContrastPalette.border.error,
      warning: highContrastPalette.border.warning,
      info: highContrastPalette.border.info,
    },
  },
  shadows: {
    // Replace soft shadows with hard outlines — translucent shadows disappear
    // against pure-white surfaces and offer no affordance in HC mode.
    none: 'none',
    xs: '0 0 0 1px #000000',
    sm: '0 0 0 1px #000000',
    md: '0 0 0 2px #000000',
    lg: '0 0 0 2px #000000',
    xl: '0 0 0 3px #000000',
    '2xl': '0 0 0 3px #000000',
    '3xl': '0 0 0 4px #000000',
    inner: 'inset 0 0 0 2px #000000',
    primary: '0 0 0 2px #000000',
    secondary: '0 0 0 2px #000000',
    success: '0 0 0 2px #006400',
    error: '0 0 0 2px #A30000',
    focus: '0 0 0 3px #CC4400',
    focusPrimary: '0 0 0 3px #CC4400',
    focusError: '0 0 0 3px #CC4400',
    focusWarning: '0 0 0 3px #CC4400',
    focusSuccess: '0 0 0 3px #CC4400',
  },
});
