import { createTheme, createThemeContract } from '@vanilla-extract/css';

import { darkTheme, lightTheme, normalTheme } from './theme';

// Token contract — flat, Bootstrap-style. No 50-950 ramps; states and tints
// are named explicitly (primary / primaryHover / primaryBgSubtle / …).
export const vars = createThemeContract({
  mode: null,

  colors: {
    primary: null,
    primaryHover: null,
    primaryActive: null,
    primaryBgSubtle: null,
    primaryBorderSubtle: null,
    primaryTextEmphasis: null,
    secondary: null,
    secondaryHover: null,
    secondaryActive: null,
    secondaryBgSubtle: null,
    secondaryBorderSubtle: null,
    secondaryTextEmphasis: null,
    success: null,
    successHover: null,
    successActive: null,
    successBgSubtle: null,
    successBorderSubtle: null,
    successTextEmphasis: null,
    danger: null,
    dangerHover: null,
    dangerActive: null,
    dangerBgSubtle: null,
    dangerBorderSubtle: null,
    dangerTextEmphasis: null,
    warning: null,
    warningHover: null,
    warningActive: null,
    warningBgSubtle: null,
    warningBorderSubtle: null,
    warningTextEmphasis: null,
    info: null,
    infoHover: null,
    infoActive: null,
    infoBgSubtle: null,
    infoBorderSubtle: null,
    infoTextEmphasis: null,
    accentPaw: null,
    accentSky: null,
    accentLeaf: null,
    gradientPrimary: null,
    gradientBrand: null,
  },

  gray: {
    '100': null,
    '200': null,
    '300': null,
    '400': null,
    '500': null,
    '600': null,
    '700': null,
    '800': null,
    '900': null,
  },

  text: {
    primary: null,
    secondary: null,
    tertiary: null,
    muted: null,
    disabled: null,
    inverse: null,
    link: null,
    linkHover: null,
    danger: null,
    success: null,
    warning: null,
    info: null,
  },

  background: {
    body: null,
    surface: null,
    muted: null,
    inverse: null,
    overlay: null,
    disabled: null,
    danger: null,
    success: null,
    warning: null,
    info: null,
  },

  border: {
    width: {
      thin: null,
      base: null,
      thick: null,
    },
    radius: {
      sm: null,
      base: null,
      lg: null,
      xl: null,
      '2xl': null,
      pill: null,
    },
    color: {
      default: null,
      muted: null,
      strong: null,
      focus: null,
      danger: null,
      success: null,
      warning: null,
      info: null,
    },
  },

  shadows: {
    none: null,
    sm: null,
    base: null,
    lg: null,
    xl: null,
    inner: null,
    focus: null,
    focusDanger: null,
  },

  spacing: {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': null,
    '8': null,
  },

  typography: {
    family: {
      sans: null,
      serif: null,
      mono: null,
      display: null,
    },
    weight: {
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
    },
    size: {
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      '4xl': null,
      '5xl': null,
      '6xl': null,
      '7xl': null,
    },
    lineHeight: {
      none: null,
      tight: null,
      snug: null,
      normal: null,
      relaxed: null,
      loose: null,
    },
    letterSpacing: {
      tighter: null,
      tight: null,
      normal: null,
      wide: null,
      wider: null,
      widest: null,
    },
  },

  animations: {
    duration: {
      instant: null,
      fast: null,
      normal: null,
      slow: null,
      slower: null,
    },
    easing: {
      linear: null,
      easeIn: null,
      easeOut: null,
      easeInOut: null,
      bounce: null,
      elastic: null,
      smooth: null,
    },
  },

  transitions: {
    none: null,
    fast: null,
    base: null,
    slow: null,
  },

  breakpoints: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
  },

  zIndex: {
    base: null,
    docked: null,
    dropdown: null,
    sticky: null,
    overlay: null,
    modal: null,
    popover: null,
    toast: null,
    tooltip: null,
  },
});

const tokensFor = (theme: typeof lightTheme) => ({
  mode: theme.mode,
  colors: theme.colors,
  gray: theme.gray,
  text: theme.text,
  background: theme.background,
  border: {
    width: theme.border.width,
    radius: theme.border.radius,
    color: theme.border.color,
  },
  shadows: theme.shadows,
  spacing: {
    '0': theme.spacing[0],
    '1': theme.spacing[1],
    '2': theme.spacing[2],
    '3': theme.spacing[3],
    '4': theme.spacing[4],
    '5': theme.spacing[5],
    '6': theme.spacing[6],
    '7': theme.spacing[7],
    '8': theme.spacing[8],
  },
  typography: {
    family: theme.typography.family,
    weight: {
      light: String(theme.typography.weight.light),
      normal: String(theme.typography.weight.normal),
      medium: String(theme.typography.weight.medium),
      semibold: String(theme.typography.weight.semibold),
      bold: String(theme.typography.weight.bold),
    },
    size: theme.typography.size,
    lineHeight: {
      none: String(theme.typography.lineHeight.none),
      tight: String(theme.typography.lineHeight.tight),
      snug: String(theme.typography.lineHeight.snug),
      normal: String(theme.typography.lineHeight.normal),
      relaxed: String(theme.typography.lineHeight.relaxed),
      loose: String(theme.typography.lineHeight.loose),
    },
    letterSpacing: theme.typography.letterSpacing,
  },
  animations: theme.animations,
  transitions: theme.transitions,
  breakpoints: theme.breakpoints,
  zIndex: {
    base: String(theme.zIndex.base),
    docked: String(theme.zIndex.docked),
    dropdown: String(theme.zIndex.dropdown),
    sticky: String(theme.zIndex.sticky),
    overlay: String(theme.zIndex.overlay),
    modal: String(theme.zIndex.modal),
    popover: String(theme.zIndex.popover),
    toast: String(theme.zIndex.toast),
    tooltip: String(theme.zIndex.tooltip),
  },
});

export const lightThemeClass = createTheme(vars, tokensFor(lightTheme));
export const normalThemeClass = createTheme(vars, tokensFor(normalTheme));
export const darkThemeClass = createTheme(vars, tokensFor(darkTheme));
