// CAD lesson #7: ts-proto emits each message as **both** an `interface X`
// AND a `const X` (the message factory with encode/decode/fromJSON). That
// makes `PingV1.EchoRequest` ambiguous in type position — it resolves to
// the const factory, not the interface, and downstream consumers see the
// wrong shape.
//
// The fix, ported from `@cad/proto`, is to export each package twice:
//
//   - **Value namespace** (`PingV1`, `NotificationsV1`) — use for
//     instantiating messages, calling encode/decode/fromJSON, reading
//     enum values, AND for the gRPC service definitions + client
//     constructors that ts-proto emits with `outputServices=grpc-js`:
//
//       import { NotificationsV1 } from '@adopt-dont-shop/proto';
//       server.addService(
//         NotificationsV1.NotificationServiceService,
//         handlers,
//       );
//
//   - **Flat type-only re-exports** — for type positions:
//
//       import type { CreateNotificationRequest } from '@adopt-dont-shop/proto';
//       const req: CreateNotificationRequest = { ... };
//
// Every new .proto file added under `proto/` gets the same two-line
// treatment here. Namespace convention: `<Package><Version>` —
// `AuthV1`, `PetsV1`, ...

export * as PingV1 from './generated/proto/adopt_dont_shop/v1/ping.js';
export type { EchoRequest, EchoResponse } from './generated/proto/adopt_dont_shop/v1/ping.js';

export * as NotificationsV1 from './generated/proto/adopt_dont_shop/notifications/v1/notification.js';
export type {
  Notification,
  CreateNotificationRequest,
  CreateNotificationResponse,
  ListNotificationsRequest,
  ListNotificationsResponse,
  DismissNotificationRequest,
  DismissNotificationResponse,
  SendEmailRequest,
  SendEmailResponse,
  EmailPreferences,
  GetEmailPreferencesRequest,
  GetEmailPreferencesResponse,
  UpdateEmailPreferencesRequest,
  UpdateEmailPreferencesResponse,
  DeviceToken as NotificationsDeviceToken,
  RegisterDeviceTokenRequest,
  RegisterDeviceTokenResponse,
  UnregisterDeviceTokenRequest,
  UnregisterDeviceTokenResponse,
  ListDeviceTokensRequest,
  ListDeviceTokensResponse,
  GetNotificationRequest,
  GetNotificationResponse,
  GetUnreadCountRequest,
  GetUnreadCountResponse,
  MarkAllReadRequest,
  MarkAllReadResponse,
  DeleteNotificationRequest,
  DeleteNotificationResponse,
  NotificationPreferences,
  GetNotificationPreferencesRequest,
  GetNotificationPreferencesResponse,
  UpdateNotificationPreferencesRequest,
  UpdateNotificationPreferencesResponse,
  ResetNotificationPreferencesRequest,
  ResetNotificationPreferencesResponse,
  CleanupExpiredNotificationsRequest,
  CleanupExpiredNotificationsResponse,
  EmailTemplate,
  ListEmailTemplatesRequest,
  ListEmailTemplatesResponse,
  GetEmailTemplateRequest,
  GetEmailTemplateResponse,
  CreateEmailTemplateRequest,
  CreateEmailTemplateResponse,
  UpdateEmailTemplateRequest,
  UpdateEmailTemplateResponse,
  DeleteEmailTemplateRequest,
  DeleteEmailTemplateResponse,
  PreviewEmailTemplateRequest,
  PreviewEmailTemplateResponse,
  BroadcastCohort,
  BroadcastRequest,
  BroadcastResponse,
  NotificationServiceServer,
  NotificationServiceClient,
} from './generated/proto/adopt_dont_shop/notifications/v1/notification.js';

export * as AuthV1 from './generated/proto/adopt_dont_shop/auth/v1/auth.js';
export type {
  Principal as AuthPrincipal,
  User as AuthUser,
  TokenPair,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  LogoutResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  ValidateTokenRequest,
  ValidateTokenResponse,
  GetMeRequest,
  GetMeResponse,
  AssignRoleRequest,
  AssignRoleResponse,
  RegisterRequest,
  RegisterResponse,
  ProvisionInvitedUserRequest,
  ProvisionInvitedUserResponse,
  VerifyEmailRequest,
  VerifyEmailResponse,
  ResendVerificationRequest,
  ResendVerificationResponse,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  RedeemInvitationRequest,
  RedeemInvitationResponse,
  ChangePasswordRequest,
  ChangePasswordResponse,
  SetupTwoFactorRequest,
  SetupTwoFactorResponse,
  EnableTwoFactorRequest,
  EnableTwoFactorResponse,
  DisableTwoFactorRequest,
  DisableTwoFactorResponse,
  RegenerateBackupCodesRequest,
  RegenerateBackupCodesResponse,
  UpdateAccountRequest,
  UpdateAccountResponse,
  Session as AuthSession,
  ListSessionsRequest,
  ListSessionsResponse,
  RevokeSessionRequest,
  RevokeSessionResponse,
  PrivacyPreferences,
  GetPrivacyPreferencesRequest,
  GetPrivacyPreferencesResponse,
  UpdatePrivacyPreferencesRequest,
  UpdatePrivacyPreferencesResponse,
  ResetPrivacyPreferencesRequest,
  ResetPrivacyPreferencesResponse,
  SearchUsersRequest,
  SearchUsersResponse,
  AdminGetUserRequest,
  AdminGetUserResponse,
  AdminUpdateUserRequest,
  AdminUpdateUserResponse,
  AdminCreateUserRequest,
  AdminCreateUserResponse,
  DeactivateUserRequest,
  DeactivateUserResponse,
  ReactivateUserRequest,
  ReactivateUserResponse,
  AdminResetPasswordRequest,
  AdminResetPasswordResponse,
  ExportUserDataRequest,
  ExportUserDataResponse,
  RequestAccountDeletionRequest,
  RequestAccountDeletionResponse,
  AdminSessionInfo,
  AdminListSessionsRequest,
  AdminListSessionsResponse,
  AdminRevokeSessionRequest,
  AdminRevokeSessionResponse,
  AdminRevokeAllUserSessionsRequest,
  AdminRevokeAllUserSessionsResponse,
  AdminLockAccountRequest,
  AdminLockAccountResponse,
  AdminUnlockAccountRequest,
  AdminUnlockAccountResponse,
  IpRule,
  ListIpRulesRequest,
  ListIpRulesResponse,
  CreateIpRuleRequest,
  CreateIpRuleResponse,
  DeleteIpRuleRequest,
  DeleteIpRuleResponse,
  GetUserStatisticsRequest,
  GetUserStatisticsResponse,
  GetUserPermissionsRequest,
  GetUserPermissionsResponse,
  BulkUpdateUsersRequest,
  BulkUpdateUsersResponse,
  FieldPermission as AuthFieldPermission,
  FieldPermissionOverrideInput,
  GetFieldPermissionDefaultsRequest,
  GetFieldPermissionDefaultsResponse,
  GetFieldPermissionDefaultsForRoleRequest,
  GetFieldPermissionDefaultsForRoleResponse,
  ListFieldPermissionOverridesRequest,
  ListFieldPermissionOverridesResponse,
  ListFieldPermissionOverridesForRoleRequest,
  ListFieldPermissionOverridesForRoleResponse,
  UpsertFieldPermissionRequest,
  UpsertFieldPermissionResponse,
  BulkUpsertFieldPermissionsRequest,
  BulkUpsertFieldPermissionsResponse,
  DeleteFieldPermissionRequest,
  DeleteFieldPermissionResponse,
  ListUserIdsByCohortRequest,
  ListUserIdsByCohortResponse,
  AuthServiceServer,
  AuthServiceClient,
} from './generated/proto/adopt_dont_shop/auth/v1/auth.js';

export * as PetsV1 from './generated/proto/adopt_dont_shop/pets/v1/pet.js';
export type {
  Pet,
  PetStatusTransition,
  CreatePetRequest,
  CreatePetResponse,
  GetPetRequest,
  GetPetResponse,
  ListPetsRequest,
  ListPetsResponse,
  UpdatePetRequest,
  UpdatePetResponse,
  UpdatePetStatusRequest,
  UpdatePetStatusResponse,
  DeletePetRequest,
  DeletePetResponse,
  GetPetStatsRequest,
  GetPetStatsResponse,
  ListPetFavoritersRequest,
  ListPetFavoritersResponse,
  AddFavoriteRequest,
  AddFavoriteResponse,
  RemoveFavoriteRequest,
  RemoveFavoriteResponse,
  GetFavoriteStatusRequest,
  GetFavoriteStatusResponse,
  ListUserFavoritesRequest,
  ListUserFavoritesResponse,
  GetAdoptionTrendRequest,
  AdoptionTrendPoint,
  GetAdoptionTrendResponse,
  GetAdoptionsByTypeRequest,
  AdoptionsByTypeCount,
  GetAdoptionsByTypeResponse,
  GetTopRescuesByAdoptionsRequest,
  RescueAdoptionCount,
  GetTopRescuesByAdoptionsResponse,
  GetTopBreedsByAdoptionsRequest,
  BreedAdoptionCount,
  GetTopBreedsByAdoptionsResponse,
  PetServiceServer,
  PetServiceClient,
} from './generated/proto/adopt_dont_shop/pets/v1/pet.js';

export * as RescueV1 from './generated/proto/adopt_dont_shop/rescue/v1/rescue.js';
export type {
  Rescue,
  Invitation,
  CreateRescueRequest,
  CreateRescueResponse,
  GetRescueRequest,
  GetRescueResponse,
  ListRescuesRequest,
  ListRescuesResponse,
  UpdateRescueRequest,
  UpdateRescueResponse,
  VerifyRescueRequest,
  VerifyRescueResponse,
  InviteStaffRequest,
  InviteStaffResponse,
  StaffMember,
  GetMyStaffMembershipRequest,
  GetMyStaffMembershipResponse,
  ListStaffMembersRequest,
  ListStaffMembersResponse,
  CreateStaffMemberRequest,
  CreateStaffMemberResponse,
  UpdateStaffMemberRequest,
  UpdateStaffMemberResponse,
  RemoveStaffMemberRequest,
  RemoveStaffMemberResponse,
  FosterPlacement,
  CreateFosterPlacementRequest,
  CreateFosterPlacementResponse,
  ListFosterPlacementsRequest,
  ListFosterPlacementsResponse,
  GetFosterPlacementRequest,
  GetFosterPlacementResponse,
  EndFosterPlacementRequest,
  EndFosterPlacementResponse,
  GetInvitationByTokenRequest,
  GetInvitationByTokenResponse,
  AcceptInvitationRequest,
  AcceptInvitationResponse,
  ListRescueInvitationsRequest,
  ListRescueInvitationsResponse,
  CancelRescueInvitationRequest,
  CancelRescueInvitationResponse,
  ApplicationQuestion,
  ListApplicationQuestionsRequest,
  ListApplicationQuestionsResponse,
  CreateApplicationQuestionRequest,
  CreateApplicationQuestionResponse,
  DeleteApplicationQuestionRequest,
  DeleteApplicationQuestionResponse,
  UpdateRescuePlanRequest,
  UpdateRescuePlanResponse,
  GetRescueStatisticsRequest,
  GetRescueStatisticsResponse,
  RescueStatistics,
  CountRescuesRequest,
  CountRescuesResponse,
  SendRescueEmailRequest,
  SendRescueEmailResponse,
  EventType,
  EventStatus,
  EventLocation,
  RescueEvent,
  RescueEventAttendee,
  RescueEventAnalytics,
  ListEventsRequest,
  ListEventsResponse,
  GetEventRequest,
  GetEventResponse,
  CreateEventRequest,
  CreateEventResponse,
  UpdateEventRequest,
  UpdateEventResponse,
  DeleteEventRequest,
  DeleteEventResponse,
  GetEventAttendeesRequest,
  GetEventAttendeesResponse,
  AddEventAttendeeRequest,
  AddEventAttendeeResponse,
  CheckInAttendeeRequest,
  CheckInAttendeeResponse,
  GetEventAnalyticsRequest,
  GetEventAnalyticsResponse,
  RescueServiceServer,
  RescueServiceClient,
} from './generated/proto/adopt_dont_shop/rescue/v1/rescue.js';

export * as ApplicationsV1 from './generated/proto/adopt_dont_shop/applications/v1/application.js';
export type {
  Application,
  TimelineEntry,
  StartDraftRequest,
  StartDraftResponse,
  SaveDraftAnswersRequest,
  SaveDraftAnswersResponse,
  SubmitDraftRequest,
  SubmitDraftResponse,
  StartReviewRequest,
  StartReviewResponse,
  ScheduleHomeVisitRequest,
  ScheduleHomeVisitResponse,
  CompleteHomeVisitRequest,
  CompleteHomeVisitResponse,
  ApproveRequest,
  ApproveResponse,
  RejectRequest,
  RejectResponse,
  WithdrawRequest,
  WithdrawResponse,
  MarkAdoptedRequest,
  MarkAdoptedResponse,
  GetApplicationRequest,
  GetApplicationResponse,
  ListApplicationsRequest,
  ListApplicationsResponse,
  GetStatsRequest,
  GetStatsResponse,
  CountAdoptedAdoptersRequest,
  CountAdoptedAdoptersResponse,
  Document,
  AddDocumentRequest,
  AddDocumentResponse,
  ListDocumentsRequest,
  ListDocumentsResponse,
  RemoveDocumentRequest,
  RemoveDocumentResponse,
  GetApplicationDefaultsRequest,
  GetApplicationDefaultsResponse,
  UpdateApplicationDefaultsRequest,
  UpdateApplicationDefaultsResponse,
  GetApplicationDraftRequest,
  GetApplicationDraftResponse,
  SaveApplicationDraftRequest,
  SaveApplicationDraftResponse,
  DeleteApplicationDraftRequest,
  DeleteApplicationDraftResponse,
  ApplicationServiceServer,
  ApplicationServiceClient,
} from './generated/proto/adopt_dont_shop/applications/v1/application.js';

export * as ChatV1 from './generated/proto/adopt_dont_shop/chat/v1/chat.js';
export type {
  Chat,
  Message,
  MessageReaction,
  OpenChatRequest,
  OpenChatResponse,
  SendMessageRequest,
  SendMessageResponse,
  ListMessagesRequest,
  ListMessagesResponse,
  ListChatsRequest,
  ListChatsResponse,
  MarkReadRequest,
  MarkReadResponse,
  ReactRequest,
  ReactResponse,
  SearchChatsRequest,
  SearchChatsResponse,
  SearchChatHit,
  GetChatUnreadCountRequest,
  GetChatUnreadCountResponse,
  DeleteMessageRequest,
  DeleteMessageResponse,
  GetChatRequest,
  GetChatResponse,
  DeleteChatRequest,
  DeleteChatResponse,
  ChatServiceServer,
  ChatServiceClient,
} from './generated/proto/adopt_dont_shop/chat/v1/chat.js';

export * as MatchingV1 from './generated/proto/adopt_dont_shop/matching/v1/matching.js';
export type {
  SwipeSession,
  PetCandidate,
  SwipeActionRecord,
  StartSessionRequest,
  StartSessionResponse,
  EndSessionRequest,
  EndSessionResponse,
  RecommendRequest,
  RecommendResponse,
  RecordSwipeRequest,
  RecordSwipeResponse,
  SearchPetsRequest,
  SearchPetsResponse,
  ListSwipeHistoryRequest,
  ListSwipeHistoryResponse,
  MatchProfile,
  GetMatchProfileRequest,
  GetMatchProfileResponse,
  UpsertMatchProfileRequest,
  UpsertMatchProfileResponse,
  SwipeStats,
  GetUserSwipeStatsRequest,
  GetUserSwipeStatsResponse,
  GetSessionStatsRequest,
  GetSessionStatsResponse,
  TopPick,
  TopPickReasonChip,
  GetTopPicksRequest,
  GetTopPicksResponse,
  MatchingServiceServer,
  MatchingServiceClient,
} from './generated/proto/adopt_dont_shop/matching/v1/matching.js';

export * as ModerationV1 from './generated/proto/adopt_dont_shop/moderation/v1/moderation.js';
export type {
  Report,
  ReportStatusTransition,
  ModeratorAction,
  Evidence,
  UserSanction,
  SupportTicket,
  SupportTicketResponse,
  FileReportRequest,
  FileReportResponse,
  GetReportRequest,
  GetReportResponse,
  ListReportsRequest,
  ListReportsResponse,
  AssignReportRequest,
  AssignReportResponse,
  ResolveReportRequest,
  ResolveReportResponse,
  LogModeratorActionRequest,
  LogModeratorActionResponse,
  ListModeratorActionsRequest,
  ListModeratorActionsResponse,
  AddEvidenceRequest,
  AddEvidenceResponse,
  IssueSanctionRequest,
  IssueSanctionResponse,
  ListUserSanctionsRequest,
  ListUserSanctionsResponse,
  AppealSanctionRequest,
  AppealSanctionResponse,
  AcknowledgeSanctionRequest,
  AcknowledgeSanctionResponse,
  OpenSupportTicketRequest,
  OpenSupportTicketResponse,
  GetSupportTicketRequest,
  GetSupportTicketResponse,
  ListSupportTicketsRequest,
  ListSupportTicketsResponse,
  RespondToTicketRequest,
  RespondToTicketResponse,
  AssignSupportTicketRequest,
  AssignSupportTicketResponse,
  ModerationServiceServer,
  ModerationServiceClient,
} from './generated/proto/adopt_dont_shop/moderation/v1/moderation.js';

export * as AuditV1 from './generated/proto/adopt_dont_shop/audit/v1/audit.js';
export type {
  AuditEvent,
  QueryRequest as AuditQueryRequest,
  QueryResponse as AuditQueryResponse,
  GetByTargetRequest as AuditGetByTargetRequest,
  GetByTargetResponse as AuditGetByTargetResponse,
  SavedReport as AuditSavedReport,
  ReportTemplate as AuditReportTemplate,
  ListSavedReportsRequest as AuditListSavedReportsRequest,
  ListSavedReportsResponse as AuditListSavedReportsResponse,
  GetSavedReportRequest as AuditGetSavedReportRequest,
  GetSavedReportResponse as AuditGetSavedReportResponse,
  CreateSavedReportRequest as AuditCreateSavedReportRequest,
  CreateSavedReportResponse as AuditCreateSavedReportResponse,
  UpdateSavedReportRequest as AuditUpdateSavedReportRequest,
  UpdateSavedReportResponse as AuditUpdateSavedReportResponse,
  DeleteSavedReportRequest as AuditDeleteSavedReportRequest,
  DeleteSavedReportResponse as AuditDeleteSavedReportResponse,
  ListReportTemplatesRequest as AuditListReportTemplatesRequest,
  ListReportTemplatesResponse as AuditListReportTemplatesResponse,
  ReportScheduleRecipient as AuditReportScheduleRecipient,
  ReportSchedule as AuditReportSchedule,
  UpsertReportScheduleRequest as AuditUpsertReportScheduleRequest,
  UpsertReportScheduleResponse as AuditUpsertReportScheduleResponse,
  ReportShare as AuditReportShare,
  CreateReportShareRequest as AuditCreateReportShareRequest,
  CreateReportShareResponse as AuditCreateReportShareResponse,
  GdprErasureRequest as AuditGdprErasureRequest,
  GetGdprErasureRequestRequest as AuditGetGdprErasureRequestRequest,
  GetGdprErasureRequestResponse as AuditGetGdprErasureRequestResponse,
  AuditQueryServiceServer,
  AuditQueryServiceClient,
} from './generated/proto/adopt_dont_shop/audit/v1/audit.js';

export * as CmsV1 from './generated/proto/adopt_dont_shop/cms/v1/cms.js';
export type {
  Content as CmsContent,
  ContentVersion as CmsContentVersion,
  Menu as CmsMenu,
  ListPublicContentRequest as CmsListPublicContentRequest,
  ListPublicContentResponse as CmsListPublicContentResponse,
  GetPublicContentBySlugRequest as CmsGetPublicContentBySlugRequest,
  GetPublicContentBySlugResponse as CmsGetPublicContentBySlugResponse,
  ListContentRequest as CmsListContentRequest,
  ListContentResponse as CmsListContentResponse,
  GetContentRequest as CmsGetContentRequest,
  GetContentResponse as CmsGetContentResponse,
  GetContentBySlugRequest as CmsGetContentBySlugRequest,
  GetContentBySlugResponse as CmsGetContentBySlugResponse,
  CreateContentRequest as CmsCreateContentRequest,
  CreateContentResponse as CmsCreateContentResponse,
  UpdateContentRequest as CmsUpdateContentRequest,
  UpdateContentResponse as CmsUpdateContentResponse,
  DeleteContentRequest as CmsDeleteContentRequest,
  DeleteContentResponse as CmsDeleteContentResponse,
  PublishContentRequest as CmsPublishContentRequest,
  PublishContentResponse as CmsPublishContentResponse,
  UnpublishContentRequest as CmsUnpublishContentRequest,
  UnpublishContentResponse as CmsUnpublishContentResponse,
  ArchiveContentRequest as CmsArchiveContentRequest,
  ArchiveContentResponse as CmsArchiveContentResponse,
  GetVersionHistoryRequest as CmsGetVersionHistoryRequest,
  GetVersionHistoryResponse as CmsGetVersionHistoryResponse,
  RestoreVersionRequest as CmsRestoreVersionRequest,
  RestoreVersionResponse as CmsRestoreVersionResponse,
  ListMenusRequest as CmsListMenusRequest,
  ListMenusResponse as CmsListMenusResponse,
  GetMenuRequest as CmsGetMenuRequest,
  GetMenuResponse as CmsGetMenuResponse,
  CreateMenuRequest as CmsCreateMenuRequest,
  CreateMenuResponse as CmsCreateMenuResponse,
  UpdateMenuRequest as CmsUpdateMenuRequest,
  UpdateMenuResponse as CmsUpdateMenuResponse,
  DeleteMenuRequest as CmsDeleteMenuRequest,
  DeleteMenuResponse as CmsDeleteMenuResponse,
  CmsServiceServer,
  CmsServiceClient,
} from './generated/proto/adopt_dont_shop/cms/v1/cms.js';
