import mongoose from 'mongoose';

/**
 * Function to generate a new MongoDB ObjectId.
 *
 * This utility function leverages Mongoose, a MongoDB object modeling tool, to create a new ObjectId. MongoDB ObjectIds
 * are used as unique identifiers for documents within a collection. Generating an ObjectId can be useful for operations
 * where an identifier is needed before creating a document, or when manually creating references between documents.
 *
 * @returns {mongoose.Types.ObjectId} - A new, unique ObjectId instance generated by Mongoose. This ObjectId can be used
 * directly in MongoDB operations through Mongoose models or in any context where a MongoDB ObjectId is required.
 *
 * The returned ObjectId follows the standard 12-byte format used by MongoDB, ensuring compatibility with MongoDB's
 * expectations for document identifiers. This function abstracts away the need to directly interact with the MongoDB
 * driver for ObjectId generation, providing a convenient method accessible through Mongoose's API.
 */

const generateObjectId = (input) => {
	if (typeof input === 'string' && mongoose.Types.ObjectId.isValid(input)) {
		return new mongoose.Types.ObjectId(input);
	} else if (typeof input === 'number') {
		// createFromTime takes a time in seconds since the Unix epoch
		return mongoose.Types.ObjectId.createFromTime(Math.floor(input / 1000));
	}
	return new mongoose.Types.ObjectId();
};

export { generateObjectId };
