import bcrypt from 'bcrypt';
import User, { UserStatus, UserType } from '../models/User';

const testUsers = [
  {
    userId: 'user_superadmin_001',
    firstName: 'Super',
    lastName: 'Admin',
    email: 'superadmin@adoptdontshop.dev',
    userType: UserType.ADMIN,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'New York',
    timezone: 'America/New_York',
    language: 'en',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_admin_001',
    firstName: 'System',
    lastName: 'Administrator',
    email: 'admin@adoptdontshop.dev',
    userType: UserType.ADMIN,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'San Francisco',
    timezone: 'America/Los_Angeles',
    language: 'en',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_moderator_001',
    firstName: 'Content',
    lastName: 'Moderator',
    email: 'moderator@adoptdontshop.dev',
    userType: UserType.MODERATOR,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Chicago',
    timezone: 'America/Chicago',
    language: 'en',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_rescue_admin_001',
    firstName: 'Rescue',
    lastName: 'Manager',
    email: 'rescue.manager@pawsrescue.dev',
    userType: UserType.RESCUE_STAFF,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Austin',
    timezone: 'America/Chicago',
    language: 'en',
    bio: 'Passionate about animal rescue and finding homes for pets in need.',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_rescue_staff_001',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@pawsrescue.dev',
    userType: UserType.RESCUE_STAFF,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Austin',
    timezone: 'America/Chicago',
    language: 'en',
    bio: 'Veterinary technician helping rescued animals get healthy and ready for adoption.',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_rescue_admin_002',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria@happytailsrescue.dev',
    userType: UserType.RESCUE_STAFF,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Miami',
    timezone: 'America/New_York',
    language: 'en',
    bio: 'Director of Happy Tails Rescue, specializing in senior dog adoption.',
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_adopter_001',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@gmail.com',
    userType: UserType.ADOPTER,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Denver',
    addressLine1: '123 Main Street',
    postalCode: '80202',
    timezone: 'America/Denver',
    language: 'en',
    bio: 'Looking to adopt a friendly dog for my family.',
    dateOfBirth: new Date('1985-06-15'),
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_adopter_002',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@yahoo.com',
    userType: UserType.ADOPTER,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Portland',
    addressLine1: '456 Oak Avenue',
    postalCode: '97201',
    timezone: 'America/Los_Angeles',
    language: 'en',
    bio: 'Cat lover looking for a special feline companion.',
    dateOfBirth: new Date('1992-03-22'),
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_adopter_003',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@outlook.com',
    userType: UserType.ADOPTER,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Seattle',
    addressLine1: '789 Pine Street',
    postalCode: '98101',
    timezone: 'America/Los_Angeles',
    language: 'en',
    bio: 'Experienced dog owner looking for an active companion for hiking.',
    dateOfBirth: new Date('1988-11-10'),
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
  {
    userId: 'user_adopter_004',
    firstName: 'Jessica',
    lastName: 'Wilson',
    email: 'jessica.wilson@gmail.com',
    userType: UserType.ADOPTER,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    country: 'US',
    city: 'Boston',
    addressLine1: '321 Elm Street',
    postalCode: '02101',
    timezone: 'America/New_York',
    language: 'en',
    bio: 'First-time pet owner looking for a gentle, well-trained pet.',
    dateOfBirth: new Date('1990-07-18'),
    termsAcceptedAt: new Date(),
    privacyPolicyAcceptedAt: new Date(),
  },
];

export async function seedUsers() {
  const hashedPassword = await bcrypt.hash('DevPassword123!', 12);

  for (const userData of testUsers) {
    await User.findOrCreate({
      where: { email: userData.email },
      defaults: {
        ...userData,
        password: hashedPassword,
        loginAttempts: 0,
        privacySettings: {
          showProfile: true,
          showLocation: false,
          allowMessages: true,
        },
        notificationPreferences: {
          email: true,
          push: true,
          sms: false,
          applicationUpdates: true,
          chatMessages: true,
          newPetAlerts: true,
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
  }

  // eslint-disable-next-line no-console
  console.log(`✅ Created ${testUsers.length} test users (password: DevPassword123!)`);
}
