import ApplicationQuestion, {
  QuestionCategory,
  QuestionScope,
  QuestionType,
} from '../models/ApplicationQuestion';
import { generateCryptoUuid as uuidv4 } from '../utils/uuid-helpers';

type CoreQuestionSeed = {
  question_id: string;
  question_key: string;
  category: QuestionCategory;
  question_type: QuestionType;
  question_text: string;
  help_text: string | null;
  placeholder: string | null;
  options: string[] | null;
  display_order: number;
  is_required: boolean;
  is_enabled: boolean;
};

// Core questions are platform-mandated and shown read-only to all rescues.
// Rescues may add their own questions on top of these.
const coreQuestions: CoreQuestionSeed[] = [
  // ── Personal Information ───────────────────────────────────────────────────
  // Contact details (name/email/phone/address) come from the user's account.
  // These questions capture availability and verification context.
  {
    question_id: uuidv4(),
    question_key: 'employment_status',
    category: QuestionCategory.PERSONAL_INFORMATION,
    question_type: QuestionType.SELECT,
    question_text: 'What is your current employment status?',
    help_text: 'This helps us understand how much time you have available for a pet.',
    placeholder: null,
    options: [
      'Employed full-time',
      'Employed part-time',
      'Self-employed',
      'Student',
      'Retired',
      'Homemaker',
      'Currently unemployed',
      'Other',
    ],
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'hours_from_home',
    category: QuestionCategory.PERSONAL_INFORMATION,
    question_type: QuestionType.SELECT,
    question_text: 'On a typical weekday, how many hours are you away from home?',
    help_text: null,
    placeholder: null,
    options: [
      'I work from home',
      'Less than 4 hours',
      '4–6 hours',
      '6–8 hours',
      '8–10 hours',
      'More than 10 hours',
    ],
    display_order: 1,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'willing_to_provide_id',
    category: QuestionCategory.PERSONAL_INFORMATION,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Are you willing to provide proof of identity if requested?',
    help_text: null,
    placeholder: null,
    options: null,
    display_order: 2,
    is_required: true,
    is_enabled: true,
  },

  // ── Household Information ──────────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'housing_type',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.SELECT,
    question_text: 'What type of home do you live in?',
    help_text: null,
    placeholder: null,
    options: ['House', 'Flat/Apartment', 'Bungalow', 'Terraced house', 'Farmhouse/Rural', 'Other'],
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'home_ownership',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.SELECT,
    question_text: 'Do you own or rent your home?',
    help_text: null,
    placeholder: null,
    options: ['Own', 'Rent', 'Live with family/parents', 'Other'],
    display_order: 1,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'landlord_permission',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.BOOLEAN,
    question_text: "If you rent, do you have your landlord's permission to keep a pet?",
    help_text: 'We may ask to see written confirmation before completing an adoption.',
    placeholder: null,
    options: null,
    display_order: 2,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'yard_fenced',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Do you have a fenced outdoor space?',
    help_text: 'A fully enclosed garden or yard is required for some breeds.',
    placeholder: null,
    options: null,
    display_order: 3,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'yard_size',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.SELECT,
    question_text: 'If you have an outdoor space, how large is it?',
    help_text: null,
    placeholder: null,
    options: [
      'No outdoor space',
      'Small (balcony/patio)',
      'Small garden',
      'Medium garden',
      'Large garden',
      'Very large/rural land',
    ],
    display_order: 4,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'household_members',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.TEXT,
    question_text: 'Please describe everyone who lives in your household.',
    help_text: 'Include the ages of any children.',
    placeholder: 'e.g. Two adults, one child aged 7',
    options: null,
    display_order: 5,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'household_all_agree',
    category: QuestionCategory.HOUSEHOLD_INFORMATION,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Does everyone in your household agree to adopting this pet?',
    help_text: 'It is important that all household members are on board.',
    placeholder: null,
    options: null,
    display_order: 6,
    is_required: true,
    is_enabled: true,
  },

  // ── Pet Ownership Experience ───────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'experience_level',
    category: QuestionCategory.PET_OWNERSHIP_EXPERIENCE,
    question_type: QuestionType.SELECT,
    question_text: 'How would you describe your experience level with pets?',
    help_text: null,
    placeholder: null,
    options: ['First-time owner', 'Some experience', 'Experienced', 'Very experienced'],
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'has_pets',
    category: QuestionCategory.PET_OWNERSHIP_EXPERIENCE,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Do you currently have any other pets?',
    help_text: null,
    placeholder: null,
    options: null,
    display_order: 1,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'current_pets',
    category: QuestionCategory.PET_OWNERSHIP_EXPERIENCE,
    question_type: QuestionType.TEXT,
    question_text: 'If yes, please describe your current pets.',
    help_text: 'Include species, breed, age, and whether they are neutered/spayed.',
    placeholder: 'e.g. 3-year-old neutered male Labrador',
    options: null,
    display_order: 2,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'previous_pets',
    category: QuestionCategory.PET_OWNERSHIP_EXPERIENCE,
    question_type: QuestionType.TEXT,
    question_text: 'Have you owned pets in the past? If so, what happened to them?',
    help_text: null,
    placeholder: 'e.g. Owned a dog for 12 years — passed away from old age in 2020',
    options: null,
    display_order: 3,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'training_experience',
    category: QuestionCategory.PET_OWNERSHIP_EXPERIENCE,
    question_type: QuestionType.TEXT,
    question_text: 'Do you have any experience training animals?',
    help_text: null,
    placeholder: 'e.g. Completed basic obedience classes with previous dog',
    options: null,
    display_order: 4,
    is_required: false,
    is_enabled: true,
  },

  // ── Lifestyle Compatibility ────────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'hours_alone',
    category: QuestionCategory.LIFESTYLE_COMPATIBILITY,
    question_type: QuestionType.SELECT,
    question_text: 'How many hours per day would the pet typically be left alone?',
    help_text: null,
    placeholder: null,
    options: ['Less than 2 hours', '2–4 hours', '4–6 hours', '6–8 hours', 'More than 8 hours'],
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'exercise_plan',
    category: QuestionCategory.LIFESTYLE_COMPATIBILITY,
    question_type: QuestionType.TEXT,
    question_text: 'How would you provide exercise and enrichment for the pet?',
    help_text: null,
    placeholder: 'e.g. Daily 30-minute walks, weekend hikes, playing fetch in the garden',
    options: null,
    display_order: 1,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'pet_sleeping_location',
    category: QuestionCategory.LIFESTYLE_COMPATIBILITY,
    question_type: QuestionType.SELECT,
    question_text: 'Where would the pet sleep?',
    help_text: null,
    placeholder: null,
    options: [
      'Indoors — own bed or crate',
      'Indoors — bedroom with us',
      'Outdoors — shelter provided',
      'Will vary / not decided yet',
    ],
    display_order: 2,
    is_required: true,
    is_enabled: true,
  },

  // ── Pet Care Commitment ────────────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'vet_registered',
    category: QuestionCategory.PET_CARE_COMMITMENT,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Are you registered with a local vet?',
    help_text: null,
    placeholder: null,
    options: null,
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'vet_practice',
    category: QuestionCategory.PET_CARE_COMMITMENT,
    question_type: QuestionType.TEXT,
    question_text: 'What is the name and location of your vet practice?',
    help_text: null,
    placeholder: 'e.g. Greenfield Veterinary Practice, Manchester',
    options: null,
    display_order: 1,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'pet_costs_prepared',
    category: QuestionCategory.PET_CARE_COMMITMENT,
    question_type: QuestionType.SELECT,
    question_text: 'Are you prepared for the ongoing financial costs of pet ownership?',
    help_text: 'Food, veterinary care, insurance, grooming, and supplies can add up significantly.',
    placeholder: null,
    options: [
      'Yes — I have budgeted for all ongoing costs',
      'Yes — I understand the costs involved',
      'Mostly — I may need to research some costs further',
      "I'm not fully sure what costs are involved",
    ],
    display_order: 2,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'pet_if_circumstances_change',
    category: QuestionCategory.PET_CARE_COMMITMENT,
    question_type: QuestionType.TEXT,
    question_text:
      'What would you do if your circumstances changed and you could no longer care for the pet?',
    help_text: 'e.g. moving abroad, serious illness, changes in housing.',
    placeholder: null,
    options: null,
    display_order: 3,
    is_required: true,
    is_enabled: true,
  },

  // ── References & Verification ──────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'reference_name',
    category: QuestionCategory.REFERENCES_VERIFICATION,
    question_type: QuestionType.TEXT,
    question_text: 'Please provide the full name of a personal reference.',
    help_text: 'This should be someone who knows you well but is not a family member.',
    placeholder: null,
    options: null,
    display_order: 0,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'reference_contact',
    category: QuestionCategory.REFERENCES_VERIFICATION,
    question_type: QuestionType.TEXT,
    question_text: 'What is the best way to contact your reference?',
    help_text: 'Phone number or email address.',
    placeholder: null,
    options: null,
    display_order: 1,
    is_required: false,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'reference_relationship',
    category: QuestionCategory.REFERENCES_VERIFICATION,
    question_type: QuestionType.TEXT,
    question_text: 'What is your relationship to this reference?',
    help_text: null,
    placeholder: 'e.g. Friend, colleague, neighbour',
    options: null,
    display_order: 2,
    is_required: false,
    is_enabled: true,
  },

  // ── Final Acknowledgments ──────────────────────────────────────────────────
  {
    question_id: uuidv4(),
    question_key: 'why_adopt',
    category: QuestionCategory.FINAL_ACKNOWLEDGMENTS,
    question_type: QuestionType.TEXT,
    question_text: 'Why do you want to adopt this pet?',
    help_text: 'Tell us a bit about why you feel this is the right pet for you and your household.',
    placeholder: null,
    options: null,
    display_order: 0,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'agree_home_visit',
    category: QuestionCategory.FINAL_ACKNOWLEDGMENTS,
    question_type: QuestionType.BOOLEAN,
    question_text: 'Do you agree to a home visit as part of the adoption process?',
    help_text: null,
    placeholder: null,
    options: null,
    display_order: 1,
    is_required: true,
    is_enabled: true,
  },
  {
    question_id: uuidv4(),
    question_key: 'agree_terms',
    category: QuestionCategory.FINAL_ACKNOWLEDGMENTS,
    question_type: QuestionType.BOOLEAN,
    question_text:
      'Do you confirm that all information you have provided is truthful and accurate?',
    help_text:
      'Providing false information may result in your application being declined and future applications being refused.',
    placeholder: null,
    options: null,
    display_order: 2,
    is_required: true,
    is_enabled: true,
  },
];

export async function seedApplicationQuestions(): Promise<void> {
  const existing = await ApplicationQuestion.count({
    where: { scope: QuestionScope.CORE },
  });

  if (existing > 0) {
    return;
  }

  await ApplicationQuestion.bulkCreate(
    coreQuestions.map(q => ({
      ...q,
      rescue_id: null,
      scope: QuestionScope.CORE,
      validation_rules: null,
      conditional_logic: null,
    }))
  );
}
