import { type AddConstraintOptions, type QueryInterface } from 'sequelize';
import { assertDestructiveDownAcknowledged, runInTransaction } from './_helpers';

/**
 * Baseline foreign-key batch (ADS-548).
 *
 * Every cross-table FK constraint that was omitted from the per-model baseline
 * files (00-baseline-001-* through 00-baseline-061-*) is added here so each
 * per-model file can be independently reordered.
 *
 * Existing production / staging DBs are unaffected: `scripts/rebaseline-seed-meta.ts`
 * pre-seeds SequelizeMeta to mark this file as already-applied on DBs
 * bootstrapped via the legacy `00-baseline.ts` sync() path.
 *
 * Source of truth: Sequelize model column `references` declarations and
 * `auditColumns` helper (created_by / updated_by → users SET NULL).
 * Constraints explicitly opted-out at the association level (`constraints: false`
 * with no column-level `references`) are intentionally absent.
 */
const MIGRATION_KEY = '00-baseline-999-foreign-keys';

type FkDef = {
  table: string;
  name: string;
  fields: string[];
  references: { table: string; field: string };
  onDelete?: string;
  onUpdate?: string;
};

const FK_CONSTRAINTS: FkDef[] = [
  // ── auth / RBAC ──────────────────────────────────────────────────────────
  {
    table: 'refresh_tokens',
    name: 'refresh_tokens_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'user_roles',
    name: 'user_roles_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_roles',
    name: 'user_roles_role_id_fkey',
    fields: ['role_id'],
    references: { table: 'roles', field: 'role_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'role_permissions',
    name: 'role_permissions_role_id_fkey',
    fields: ['role_id'],
    references: { table: 'roles', field: 'role_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'role_permissions',
    name: 'role_permissions_permission_id_fkey',
    fields: ['permission_id'],
    references: { table: 'permissions', field: 'permission_id' },
    onDelete: 'CASCADE',
  },

  // ── rescues ───────────────────────────────────────────────────────────────
  {
    table: 'rescues',
    name: 'rescues_verified_by_fkey',
    fields: ['verified_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'rescues',
    name: 'rescues_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'rescues',
    name: 'rescues_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'rescue_settings',
    name: 'rescue_settings_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'rescue_settings',
    name: 'rescue_settings_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'rescue_settings',
    name: 'rescue_settings_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── breeds & pets ─────────────────────────────────────────────────────────
  {
    table: 'breeds',
    name: 'breeds_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'breeds',
    name: 'breeds_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'pets',
    name: 'pets_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'pets',
    name: 'pets_breed_id_fkey',
    fields: ['breed_id'],
    references: { table: 'breeds', field: 'breed_id' },
    onDelete: 'SET NULL',
    onUpdate: 'CASCADE',
  },
  {
    table: 'pets',
    name: 'pets_secondary_breed_id_fkey',
    fields: ['secondary_breed_id'],
    references: { table: 'breeds', field: 'breed_id' },
    onDelete: 'SET NULL',
    onUpdate: 'CASCADE',
  },
  {
    table: 'pets',
    name: 'pets_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'pets',
    name: 'pets_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'pet_media',
    name: 'pet_media_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'pet_media',
    name: 'pet_media_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'pet_media',
    name: 'pet_media_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'pet_status_transitions',
    name: 'pet_status_transitions_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'CASCADE',
  },

  // ── staff & invitations ───────────────────────────────────────────────────
  {
    table: 'staff_members',
    name: 'staff_members_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'staff_members',
    name: 'staff_members_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'staff_members',
    name: 'staff_members_verified_by_fkey',
    fields: ['verified_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'staff_members',
    name: 'staff_members_added_by_fkey',
    fields: ['added_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'staff_members',
    name: 'staff_members_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'staff_members',
    name: 'staff_members_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'invitations',
    name: 'invitations_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'invitations',
    name: 'invitations_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'invitations',
    name: 'invitations_invited_by_fkey',
    fields: ['invited_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'invitations',
    name: 'invitations_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'invitations',
    name: 'invitations_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── addresses (polymorphic owner_id has no DB FK) ─────────────────────────
  {
    table: 'addresses',
    name: 'addresses_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'addresses',
    name: 'addresses_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── ratings ───────────────────────────────────────────────────────────────
  {
    table: 'ratings',
    name: 'ratings_reviewer_id_fkey',
    fields: ['reviewer_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_reviewee_id_fkey',
    fields: ['reviewee_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'ratings',
    name: 'ratings_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── applications ──────────────────────────────────────────────────────────
  {
    table: 'applications',
    name: 'applications_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'applications',
    name: 'applications_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'applications',
    name: 'applications_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'applications',
    name: 'applications_actioned_by_fkey',
    fields: ['actioned_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'applications',
    name: 'applications_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'applications',
    name: 'applications_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_answers',
    name: 'application_answers_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'application_answers',
    name: 'application_answers_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_answers',
    name: 'application_answers_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_questions',
    name: 'application_questions_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'application_questions',
    name: 'application_questions_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_questions',
    name: 'application_questions_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_references',
    name: 'application_references_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'application_references',
    name: 'application_references_contacted_by_fkey',
    fields: ['contacted_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
    onUpdate: 'CASCADE',
  },
  {
    table: 'application_references',
    name: 'application_references_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_references',
    name: 'application_references_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'application_status_transitions',
    name: 'application_status_transitions_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'application_status_transitions',
    name: 'application_status_transitions_transitioned_by_fkey',
    fields: ['transitioned_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_application_prefs',
    name: 'user_application_prefs_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_application_prefs',
    name: 'user_application_prefs_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_application_prefs',
    name: 'user_application_prefs_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── home visits ───────────────────────────────────────────────────────────
  {
    table: 'home_visits',
    name: 'home_visits_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'home_visits',
    name: 'home_visits_assigned_staff_fkey',
    fields: ['assigned_staff'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'home_visits',
    name: 'home_visits_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'home_visits',
    name: 'home_visits_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'home_visit_status_transitions',
    name: 'home_visit_status_transitions_visit_id_fkey',
    fields: ['visit_id'],
    references: { table: 'home_visits', field: 'visit_id' },
    onDelete: 'CASCADE',
  },

  // ── chat & messaging ──────────────────────────────────────────────────────
  {
    table: 'chats',
    name: 'chats_application_id_fkey',
    fields: ['application_id'],
    references: { table: 'applications', field: 'application_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'chats',
    name: 'chats_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'chats',
    name: 'chats_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'chats',
    name: 'chats_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'chats',
    name: 'chats_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'chat_participants',
    name: 'chat_participants_chat_id_fkey',
    fields: ['chat_id'],
    references: { table: 'chats', field: 'chat_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'chat_participants',
    name: 'chat_participants_participant_id_fkey',
    fields: ['participant_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'chat_participants',
    name: 'chat_participants_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'chat_participants',
    name: 'chat_participants_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'messages',
    name: 'messages_chat_id_fkey',
    fields: ['chat_id'],
    references: { table: 'chats', field: 'chat_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'messages',
    name: 'messages_sender_id_fkey',
    fields: ['sender_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'messages',
    name: 'messages_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'messages',
    name: 'messages_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'message_reactions',
    name: 'message_reactions_message_id_fkey',
    fields: ['message_id'],
    references: { table: 'messages', field: 'message_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'message_reactions',
    name: 'message_reactions_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'message_reactions',
    name: 'message_reactions_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'message_reactions',
    name: 'message_reactions_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'message_reads',
    name: 'message_reads_message_id_fkey',
    fields: ['message_id'],
    references: { table: 'messages', field: 'message_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'message_reads',
    name: 'message_reads_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
    onUpdate: 'CASCADE',
  },

  // ── file uploads ──────────────────────────────────────────────────────────
  {
    table: 'file_uploads',
    name: 'file_uploads_uploaded_by_fkey',
    fields: ['uploaded_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'file_uploads',
    name: 'file_uploads_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'file_uploads',
    name: 'file_uploads_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── notifications ─────────────────────────────────────────────────────────
  {
    table: 'notifications',
    name: 'notifications_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'notifications',
    name: 'notifications_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'notifications',
    name: 'notifications_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'device_tokens',
    name: 'device_tokens_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },

  // ── email ─────────────────────────────────────────────────────────────────
  {
    table: 'email_templates',
    name: 'email_templates_parent_template_id_fkey',
    fields: ['parent_template_id'],
    references: { table: 'email_templates', field: 'template_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_templates',
    name: 'email_templates_last_modified_by_fkey',
    fields: ['last_modified_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_templates',
    name: 'email_templates_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_templates',
    name: 'email_templates_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_template_versions',
    name: 'email_template_versions_template_id_fkey',
    fields: ['template_id'],
    references: { table: 'email_templates', field: 'template_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'email_template_versions',
    name: 'email_template_versions_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_template_versions',
    name: 'email_template_versions_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_queue',
    name: 'email_queue_template_id_fkey',
    fields: ['template_id'],
    references: { table: 'email_templates', field: 'template_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_queue',
    name: 'email_queue_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_queue',
    name: 'email_queue_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_queue',
    name: 'email_queue_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_preferences',
    name: 'email_preferences_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'email_preferences',
    name: 'email_preferences_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'email_preferences',
    name: 'email_preferences_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── reports & moderation ──────────────────────────────────────────────────
  {
    table: 'reports',
    name: 'reports_reporter_id_fkey',
    fields: ['reporter_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_reported_user_id_fkey',
    fields: ['reported_user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_assigned_moderator_fkey',
    fields: ['assigned_moderator'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_resolved_by_fkey',
    fields: ['resolved_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_escalated_to_fkey',
    fields: ['escalated_to'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'reports',
    name: 'reports_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_status_transitions',
    name: 'report_status_transitions_report_id_fkey',
    fields: ['report_id'],
    references: { table: 'reports', field: 'report_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_moderator_id_fkey',
    fields: ['moderator_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_report_id_fkey',
    fields: ['report_id'],
    references: { table: 'reports', field: 'report_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_target_user_id_fkey',
    fields: ['target_user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_reversed_by_fkey',
    fields: ['reversed_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderator_actions',
    name: 'moderator_actions_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  // polymorphic parent_id has no DB-level FK; audit columns only
  {
    table: 'moderation_evidence',
    name: 'moderation_evidence_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'moderation_evidence',
    name: 'moderation_evidence_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_issued_by_fkey',
    fields: ['issued_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_report_id_fkey',
    fields: ['report_id'],
    references: { table: 'reports', field: 'report_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_moderator_action_id_fkey',
    fields: ['moderator_action_id'],
    references: { table: 'moderator_actions', field: 'action_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_appeal_resolved_by_fkey',
    fields: ['appeal_resolved_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_revoked_by_fkey',
    fields: ['revoked_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_sanctions',
    name: 'user_sanctions_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── support ───────────────────────────────────────────────────────────────
  {
    table: 'support_tickets',
    name: 'support_tickets_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_tickets',
    name: 'support_tickets_assigned_to_fkey',
    fields: ['assigned_to'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_tickets',
    name: 'support_tickets_escalated_to_fkey',
    fields: ['escalated_to'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_tickets',
    name: 'support_tickets_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_tickets',
    name: 'support_tickets_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_ticket_responses',
    name: 'support_ticket_responses_ticket_id_fkey',
    fields: ['ticket_id'],
    references: { table: 'support_tickets', field: 'ticket_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'support_ticket_responses',
    name: 'support_ticket_responses_responder_id_fkey',
    fields: ['responder_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_ticket_responses',
    name: 'support_ticket_responses_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'support_ticket_responses',
    name: 'support_ticket_responses_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── swipe interface ───────────────────────────────────────────────────────
  {
    table: 'swipe_sessions',
    name: 'swipe_sessions_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'swipe_actions',
    name: 'swipe_actions_session_id_fkey',
    fields: ['session_id'],
    references: { table: 'swipe_sessions', field: 'session_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'swipe_actions',
    name: 'swipe_actions_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'swipe_actions',
    name: 'swipe_actions_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'CASCADE',
  },

  // ── user preferences & consents ───────────────────────────────────────────
  {
    table: 'user_favorites',
    name: 'user_favorites_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'user_favorites',
    name: 'user_favorites_pet_id_fkey',
    fields: ['pet_id'],
    references: { table: 'pets', field: 'pet_id' },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  {
    table: 'user_consents',
    name: 'user_consents_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_consents',
    name: 'user_consents_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_consents',
    name: 'user_consents_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_notification_prefs',
    name: 'user_notification_prefs_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_notification_prefs',
    name: 'user_notification_prefs_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_notification_prefs',
    name: 'user_notification_prefs_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_privacy_prefs',
    name: 'user_privacy_prefs_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'user_privacy_prefs',
    name: 'user_privacy_prefs_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'user_privacy_prefs',
    name: 'user_privacy_prefs_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── idempotency ───────────────────────────────────────────────────────────
  {
    table: 'idempotency_keys',
    name: 'idempotency_keys_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── analytics reports ─────────────────────────────────────────────────────
  {
    table: 'report_templates',
    name: 'report_templates_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_templates',
    name: 'report_templates_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_templates',
    name: 'report_templates_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'saved_reports',
    name: 'saved_reports_user_id_fkey',
    fields: ['user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'saved_reports',
    name: 'saved_reports_rescue_id_fkey',
    fields: ['rescue_id'],
    references: { table: 'rescues', field: 'rescue_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'saved_reports',
    name: 'saved_reports_template_id_fkey',
    fields: ['template_id'],
    references: { table: 'report_templates', field: 'template_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'saved_reports',
    name: 'saved_reports_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'saved_reports',
    name: 'saved_reports_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_shares',
    name: 'report_shares_saved_report_id_fkey',
    fields: ['saved_report_id'],
    references: { table: 'saved_reports', field: 'saved_report_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'report_shares',
    name: 'report_shares_shared_with_user_id_fkey',
    fields: ['shared_with_user_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_shares',
    name: 'report_shares_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'report_shares',
    name: 'report_shares_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'scheduled_reports',
    name: 'scheduled_reports_saved_report_id_fkey',
    fields: ['saved_report_id'],
    references: { table: 'saved_reports', field: 'saved_report_id' },
    onDelete: 'CASCADE',
  },
  {
    table: 'scheduled_reports',
    name: 'scheduled_reports_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'scheduled_reports',
    name: 'scheduled_reports_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },

  // ── CMS ───────────────────────────────────────────────────────────────────
  {
    table: 'cms_content',
    name: 'cms_content_author_id_fkey',
    fields: ['author_id'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'cms_content',
    name: 'cms_content_last_modified_by_fkey',
    fields: ['last_modified_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'cms_content',
    name: 'cms_content_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'cms_content',
    name: 'cms_content_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'cms_navigation_menus',
    name: 'cms_navigation_menus_created_by_fkey',
    fields: ['created_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
  {
    table: 'cms_navigation_menus',
    name: 'cms_navigation_menus_updated_by_fkey',
    fields: ['updated_by'],
    references: { table: 'users', field: 'user_id' },
    onDelete: 'SET NULL',
  },
];

export default {
  up: async (queryInterface: QueryInterface) => {
    await runInTransaction(queryInterface, async t => {
      for (const fk of FK_CONSTRAINTS) {
        // Sequelize's AddForeignKeyConstraintOptions types onDelete/onUpdate as required strings,
        // but the runtime emits the clauses only when truthy — omitting onUpdate is how we let
        // Postgres apply its NO ACTION default to match sync()'s output for non-belongsTo FKs.
        const options = {
          type: 'foreign key' as const,
          fields: fk.fields,
          name: fk.name,
          references: fk.references,
          ...(fk.onDelete ? { onDelete: fk.onDelete } : {}),
          ...(fk.onUpdate ? { onUpdate: fk.onUpdate } : {}),
          transaction: t,
        } as AddConstraintOptions;
        await queryInterface.addConstraint(fk.table, options);
      }
    });
  },

  down: async (queryInterface: QueryInterface) => {
    assertDestructiveDownAcknowledged(MIGRATION_KEY);
    await runInTransaction(queryInterface, async t => {
      for (const fk of [...FK_CONSTRAINTS].reverse()) {
        await queryInterface.removeConstraint(fk.table, fk.name, { transaction: t });
      }
    });
  },
};
