import type { QueryInterface, Transaction } from 'sequelize';
import { runInTransaction } from './_helpers';

/**
 * Follow-up to ADS-422 (PR #421): backfill the broken `/uploads/<filename>`
 * URL shape that the pre-#421 file-upload writer left in two JSONB columns:
 *
 *   - `messages.attachments[].url`         (chat attachments)
 *   - `applications.documents[].fileUrl`   (application documents)
 *
 * Migration #17 fixed `file_uploads.url` for the same root cause; the
 * `file_uploads` row is the canonical record, but the chat-message and
 * application-document writers also COPY the URL string into a JSONB column
 * at write time (see `chat.controller.uploadAttachment` and
 * `application.service.addDocument`). After #421 those copies are correctly
 * shaped for new rows; this migration backfills the historic copies.
 *
 * Writers (verified at the time of this migration):
 *   - chat.controller `uploadAttachment` returns `fileUploadResult.upload.url`
 *     to the client; the client then sends a `createMessage` request which
 *     stores the same URL in `messages.attachments[].url`. The upstream
 *     value is now generated by `FileUploadService.generateFileUrl` which
 *     produces `/uploads/chat/<filename>`. Already correct post-#421.
 *   - application.controller `uploadDocument` calls
 *     `ApplicationService.addDocument` with `fileUrl: uploadResult.upload.url`,
 *     stored in `applications.documents[].fileUrl`. Same upstream — already
 *     correct post-#421.
 *
 * No writer fix is needed in this migration's PR; the writers were fixed
 * by #421 via the central FileUploadService change.
 *
 * Strategy: rewrite each affected JSONB array with a single SQL UPDATE per
 * column. The prefix is fixed per table (chat uploads always go through
 * upload type `'chat'`; application uploads always through `'applications'`)
 * so we don't need to derive it from anything inside the row — unlike #17
 * which had to read `stored_filename` because `file_uploads` is shared
 * across all upload types.
 *
 * Safety:
 *
 *   - Idempotent. The transformation only fires on elements whose URL
 *     matches `^/uploads/[^/]+$` — a `/uploads/<filename>` path with NO
 *     prefix segment. After up() the rewritten URL has the form
 *     `/uploads/<prefix>/<filename>` and no longer matches, so a second
 *     run finds nothing to change.
 *   - Skips CDN / external URLs (anything starting with `http://` or
 *     `https://`) — they don't match the broken-shape regex and are left
 *     untouched.
 *   - Skips rows whose URL already has a prefix (correct shape) — same
 *     reason: doesn't match the regex.
 *   - Wrapped in a single transaction (ADS-403). Both UPDATEs commit or
 *     roll back together with the audit-log entry.
 *   - Both UPDATEs include a guard subquery (`EXISTS ... matches broken
 *     pattern`) so the row is only rewritten if at least one element is
 *     actually broken — avoids unnecessary JSONB rewrites on already-clean
 *     rows.
 *
 * Down-migration: restores the broken shape ONLY on rows where the URL has
 * the form `/uploads/<expected-prefix>/<filename>` (i.e. matches what up()
 * would have produced). Pre-existing correctly-shaped rows from other
 * sources (e.g. seeded data) are left alone because they may have a
 * filename whose prefix segment doesn't match the table's expected prefix
 * (e.g. seeders use `/uploads/documents/...` rather than
 * `/uploads/applications/...`); reverting those would corrupt them.
 *
 * Postgres-only. Uses `jsonb_array_elements`, `jsonb_agg`, and `jsonb_set`,
 * which have no SQLite equivalent. Tests skip on non-postgres dialects.
 */

type JsonbTarget = {
  /** Table containing the JSONB column. */
  table: string;
  /** JSONB column name. */
  column: string;
  /** Property inside each array element holding the URL. */
  urlKey: string;
  /** The directory prefix this table's uploads should carry. */
  prefix: string;
};

const TARGETS: ReadonlyArray<JsonbTarget> = [
  { table: 'messages', column: 'attachments', urlKey: 'url', prefix: 'chat' },
  { table: 'applications', column: 'documents', urlKey: 'fileUrl', prefix: 'applications' },
];

/**
 * Rewrite every element whose `urlKey` matches the broken shape
 * `^/uploads/<filename>$` (no prefix) to `/uploads/<prefix>/<filename>`.
 * Other elements pass through unchanged. Returns the number of rows
 * touched.
 */
const buildUpSql = ({ table, column, urlKey, prefix }: JsonbTarget): string => `
  UPDATE ${table}
     SET ${column} = (
       SELECT jsonb_agg(
         CASE
           WHEN jsonb_typeof(elem) = 'object'
            AND elem ? '${urlKey}'
            AND elem->>'${urlKey}' ~ '^/uploads/[^/]+$'
           THEN jsonb_set(
                  elem,
                  '{${urlKey}}',
                  to_jsonb('/uploads/${prefix}/' || regexp_replace(elem->>'${urlKey}', '^/uploads/', ''))
                )
           ELSE elem
         END
       )
       FROM jsonb_array_elements(${column}) AS elem
     )
   WHERE ${column} IS NOT NULL
     AND jsonb_typeof(${column}) = 'array'
     AND EXISTS (
       SELECT 1 FROM jsonb_array_elements(${column}) AS e
        WHERE jsonb_typeof(e) = 'object'
          AND e ? '${urlKey}'
          AND e->>'${urlKey}' ~ '^/uploads/[^/]+$'
     )
`;

/**
 * Reverse of buildUpSql: strip the prefix segment from any element whose
 * URL has the form `/uploads/<expected-prefix>/<filename>` — i.e. exactly
 * what up() would have written. Other elements (different prefix, CDN URL,
 * already-broken shape) pass through unchanged so we don't corrupt
 * pre-existing rows that this migration didn't touch.
 */
const buildDownSql = ({ table, column, urlKey, prefix }: JsonbTarget): string => `
  UPDATE ${table}
     SET ${column} = (
       SELECT jsonb_agg(
         CASE
           WHEN jsonb_typeof(elem) = 'object'
            AND elem ? '${urlKey}'
            AND elem->>'${urlKey}' ~ '^/uploads/${prefix}/[^/]+$'
           THEN jsonb_set(
                  elem,
                  '{${urlKey}}',
                  to_jsonb('/uploads/' || regexp_replace(elem->>'${urlKey}', '^/uploads/${prefix}/', ''))
                )
           ELSE elem
         END
       )
       FROM jsonb_array_elements(${column}) AS elem
     )
   WHERE ${column} IS NOT NULL
     AND jsonb_typeof(${column}) = 'array'
     AND EXISTS (
       SELECT 1 FROM jsonb_array_elements(${column}) AS e
        WHERE jsonb_typeof(e) = 'object'
          AND e ? '${urlKey}'
          AND e->>'${urlKey}' ~ '^/uploads/${prefix}/[^/]+$'
     )
`;

const writeAuditEntry = async (
  queryInterface: QueryInterface,
  t: Transaction,
  direction: 'up' | 'down',
  results: ReadonlyArray<{ table: string; rowsTouched: number }>
): Promise<void> => {
  // Audit log writes go through raw SQL because the AuditLog model installs
  // an append-only hook guard (see AuditLog.ts) that doesn't apply at the
  // SQL layer — and the model isn't necessarily importable from migration
  // context. Postgres trigger from migration 11 still enforces the same
  // immutability post-write.
  await queryInterface.sequelize.query(
    `INSERT INTO audit_logs (service, action, level, status, timestamp, metadata, category)
       VALUES ('migration', $1, 'INFO', 'success', NOW(), $2, 'DATA_MIGRATION')`,
    {
      bind: [
        `migration-18-fix-jsonb-url-prefix:${direction}`,
        JSON.stringify({
          migration: '18-fix-jsonb-url-prefix',
          direction,
          results,
        }),
      ] as unknown as never,
      transaction: t,
    }
  );
};

const applyAndCount = async (
  queryInterface: QueryInterface,
  t: Transaction,
  sql: string,
  table: string
): Promise<{ table: string; rowsTouched: number }> => {
  const [, meta] = await queryInterface.sequelize.query(sql, { transaction: t });
  // Postgres returns rowCount in the QueryResult metadata; Sequelize's
  // typing exposes it as `unknown` so we narrow defensively.
  const rowCount =
    typeof meta === 'object' && meta !== null && 'rowCount' in meta
      ? Number((meta as { rowCount: number | null }).rowCount ?? 0)
      : 0;
  return { table, rowsTouched: rowCount };
};

export default {
  up: async (queryInterface: QueryInterface) => {
    await runInTransaction(queryInterface, async t => {
      const results = [];
      for (const target of TARGETS) {
        const result = await applyAndCount(queryInterface, t, buildUpSql(target), target.table);
        results.push(result);
      }
      await writeAuditEntry(queryInterface, t, 'up', results);
    });
  },

  down: async (queryInterface: QueryInterface) => {
    await runInTransaction(queryInterface, async t => {
      const results = [];
      for (const target of TARGETS) {
        const result = await applyAndCount(queryInterface, t, buildDownSql(target), target.table);
        results.push(result);
      }
      await writeAuditEntry(queryInterface, t, 'down', results);
    });
  },
};
