#!/usr/bin/env node
/**
 * Bootstrap script for new contributors. Invoked via `pnpm bootstrap`.
 *
 * Flags:
 *   --skip-playwright   Skip downloading Playwright browsers (~200 MB).
 *                       Useful for CI containers or lightweight dev environments
 *                       that won't run E2E tests locally. You can install them
 *                       later with `pnpm test:e2e:install`.
 *   --start             Skip the interactive prompt and start the docker dev
 *                       stack at the end of setup.
 *   --no-start          Skip the interactive prompt and DO NOT start the stack.
 *   --enable-prepush    Skip the interactive prompt and enable the opt-in
 *                       pre-push hook (runs ci:local:quick before git push).
 *   --no-enable-prepush Skip the interactive prompt and leave the hook disabled.
 *                       Pass this in unattended setups (devcontainer, CI bots).
 */
import { execSync } from 'child_process';
import { existsSync, copyFileSync, readFileSync, writeFileSync, appendFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomBytes } from 'crypto';
import { createInterface } from 'readline';
import { platform } from 'os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const GREEN = '\x1b[32m';
const BLUE = '\x1b[34m';
const YELLOW = '\x1b[33m';

function log(message, color = RESET) {
  console.log(`${color}${message}${RESET}`);
}

function logHeader(message) {
  log('', GREEN);
  log('═'.repeat(60), GREEN);
  log(message, `${GREEN}${BOLD}`);
  log('═'.repeat(60), GREEN);
  log('', GREEN);
}

function logStep(step, message) {
  log(`${BOLD}[${step}]${RESET} ${message}`, BLUE);
}

function logSuccess(message) {
  log(`${GREEN}✓${RESET} ${message}`, GREEN);
}

function logInfo(message) {
  log(`${BLUE}ℹ${RESET} ${message}`, BLUE);
}

function logError(message) {
  log(`${YELLOW}✗${RESET} ${message}`, YELLOW);
}

function runCommand(command, options = {}) {
  try {
    execSync(command, {
      stdio: 'inherit',
      cwd: ROOT,
      ...options,
    });
  } catch (error) {
    throw new Error(`Failed to run: ${command}`);
  }
}

// Keep in sync with scripts/generate-secrets.mjs (`pnpm secrets:generate`) so
// both onboarding paths produce the same set of secrets.
const SECRET_KEYS = [
  'JWT_SECRET',
  'JWT_REFRESH_SECRET',
  'SESSION_SECRET',
  'ENCRYPTION_KEY',
  'UPLOAD_SIGNING_SECRET',
  'JWT_REPORT_SHARE_SECRET',
  'POSTGRES_PASSWORD',
  'REDIS_PASSWORD',
  'GF_SECURITY_ADMIN_PASSWORD',
];

function generateSecret(key) {
  if (key === 'ENCRYPTION_KEY') {
    // AES-256 needs exactly 32 bytes (64 hex chars).
    return randomBytes(32).toString('hex');
  }
  if (key === 'POSTGRES_PASSWORD' || key === 'REDIS_PASSWORD') {
    // These are interpolated into connection URLs (DATABASE_URL / REDIS_URL),
    // so use hex — base64 can contain + / = which break URL parsing.
    return randomBytes(24).toString('hex');
  }
  return randomBytes(32).toString('base64');
}

function isPlaceholder(value) {
  if (!value) return true;
  if (/^CHANGE/i.test(value)) return true;
  if (value.includes('your-')) return true;
  if (value.includes('change-me')) return true;
  if (value === 'replace-me') return true;
  return false;
}

function ensureSecretsInEnv(envPath) {
  const contents = readFileSync(envPath, 'utf8');
  const lines = contents.split('\n');

  const replaced = [];
  const missing = [];

  for (const key of SECRET_KEYS) {
    const idx = lines.findIndex(l => l.startsWith(`${key}=`));
    if (idx === -1) {
      missing.push(key);
      continue;
    }
    const existingValue = lines[idx].slice(key.length + 1).trim();
    if (isPlaceholder(existingValue)) {
      lines[idx] = `${key}=${generateSecret(key)}`;
      replaced.push(key);
    }
  }

  if (replaced.length === 0 && missing.length === 0) {
    return { wrote: false, replaced, missing };
  }

  let next = lines.join('\n');
  if (missing.length > 0) {
    if (!next.endsWith('\n')) next += '\n';
    next += `\n# Auto-generated by pnpm bootstrap on ${new Date().toISOString()}\n`;
    for (const key of missing) {
      next += `${key}=${generateSecret(key)}\n`;
    }
  }

  writeFileSync(envPath, next);
  return { wrote: true, replaced, missing };
}

function dockerAvailable() {
  try {
    execSync('docker info', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

// Mirror of `pnpm hooks:enable` (ADS-797): create the gitignored marker file
// that the .husky/pre-push hook checks for. Idempotent.
function enablePrepushHook() {
  const marker = join(ROOT, '.husky', '.prepush-enabled');
  writeFileSync(marker, '');
}

function promptYesNo(question, defaultYes = true) {
  if (!process.stdin.isTTY) {
    return Promise.resolve(defaultYes);
  }
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultYes ? ' (Y/n) ' : ' (y/N) ';
  return new Promise(resolve => {
    rl.question(`${question}${suffix}`, answer => {
      rl.close();
      const trimmed = answer.trim().toLowerCase();
      if (trimmed === '') {
        resolve(defaultYes);
      } else {
        resolve(trimmed === 'y' || trimmed === 'yes');
      }
    });
  });
}

async function waitForHealth(url, timeoutMs = 60000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      execSync(`curl -fsS ${url}`, { stdio: 'ignore' });
      return true;
    } catch {
      await new Promise(r => setTimeout(r, 2000));
    }
  }
  return false;
}

async function startStack() {
  logStep('9', 'Starting docker dev stack (docker compose up -d)...');
  if (!dockerAvailable()) {
    logError('Docker is not running — skipping stack start. Run `pnpm docker:dev` once Docker is up.');
    return false;
  }
  try {
    runCommand('pnpm docker:dev:detach');
  } catch (err) {
    logError(`Failed to start stack: ${err.message}`);
    return false;
  }
  runCommand('docker compose ps');
  logInfo('Waiting for nginx edge /health (up to 60s)...');
  const ok = await waitForHealth('http://localhost/health', 60000);
  if (!ok) {
    logError('Nginx edge did not become healthy within 60s. Run `pnpm docker:logs` to investigate.');
    return false;
  }
  logSuccess('Nginx edge is healthy.');
  log('', RESET);
  log('Access the stack at:', BLUE);
  log('   http://localhost:3000   # app.client', RESET);
  log('   http://localhost:3001   # app.admin', RESET);
  log('   http://localhost:3002   # app.rescue', RESET);
  log('   http://localhost          # nginx edge (apps + /api proxy)', RESET);
  log('   http://localhost:4000   # service.gateway (REST/WS API — requires `--profile services`)', RESET);
  log('', RESET);
  return true;
}

function printNextSteps() {
  log('', GREEN);
  log('Next steps:', `${BOLD}${GREEN}`);
  log('', RESET);
  log('1. Review your .env file:', BLUE);
  log('   - Secrets (including POSTGRES_PASSWORD / REDIS_PASSWORD) have been generated for you.', RESET);
  log('   - Set any third-party API keys you need.', RESET);
  log('', RESET);
  log('2. Start the development stack:', BLUE);
  log('   pnpm docker:dev          # recommended (includes database + redis)', RESET);
  log('   pnpm dev                 # native (requires local Postgres + Redis)', RESET);
  log('', RESET);
  log('For more information, see:', BLUE);
  log('   README.md                   # Project overview', RESET);
  log('   docs/README.md              # Detailed documentation', RESET);
  log('   .claude/CLAUDE.md           # Development guidelines', RESET);
  log('', GREEN);
}

async function setup() {
  logHeader("Adopt Don't Shop - Developer Setup");

  const skipPlaywright = process.argv.includes('--skip-playwright');
  const forceStart = process.argv.includes('--start');
  const forceNoStart = process.argv.includes('--no-start');
  const forceEnablePrepush = process.argv.includes('--enable-prepush');
  const forceNoEnablePrepush = process.argv.includes('--no-enable-prepush');

  try {
    // Step 1: Check Node.js version
    logStep('1', 'Checking Node.js version...');
    let nodeVersion;
    try {
      nodeVersion = execSync('node --version', { encoding: 'utf-8' }).trim();
    } catch {
      logError('Node.js is not installed');
      log('Please install Node.js v22 (see .nvmrc) from https://nodejs.org/', YELLOW);
      process.exit(1);
    }

    const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0], 10);
    if (majorVersion < 22) {
      logError(`Node.js v${majorVersion} detected, but v22+ is required (see package.json engines)`);
      log(`Current version: ${nodeVersion}`, YELLOW);
      log('Please upgrade Node.js from https://nodejs.org/', YELLOW);
      process.exit(1);
    }

    logSuccess(`Node.js ${nodeVersion} detected`);
    log('', RESET);

    // Step 1b: Ensure Corepack is enabled so `pnpm install` below resolves
    // the version pinned by package.json "packageManager" (ADS-894). CI's
    // setup-workspace action does this already; local bootstrap didn't,
    // so a fresh machine hit a cryptic "pnpm: command not found" here.
    logStep('1b', 'Ensuring Corepack is enabled...');
    try {
      execSync('corepack enable', { stdio: 'pipe', cwd: ROOT });
      execSync('corepack prepare --activate', { stdio: 'pipe', cwd: ROOT });
      logSuccess('Corepack enabled (pnpm version pinned by package.json "packageManager")');
    } catch {
      logError('Could not enable Corepack automatically (likely a permissions issue)');
      log('Run this manually, then re-run `pnpm bootstrap`:', YELLOW);
      log('  corepack enable && corepack prepare --activate', YELLOW);
      log('  (macOS/Linux: prefix with `sudo` if npm\'s global path needs it)', YELLOW);
      process.exit(1);
    }
    log('', RESET);

    // Step 2: Set up environment configuration BEFORE validation
    logStep('2', 'Setting up environment configuration...');
    const envPath = join(ROOT, '.env');
    const envExamplePath = join(ROOT, '.env.example');

    if (existsSync(envPath)) {
      logInfo('.env file already exists, leaving as-is');
    } else if (existsSync(envExamplePath)) {
      copyFileSync(envExamplePath, envPath);
      logSuccess('.env file created from .env.example');
    } else {
      logError('.env.example not found');
      throw new Error('.env.example is missing from the repository');
    }

    const result = ensureSecretsInEnv(envPath);
    if (result.replaced.length > 0) {
      logSuccess(`Replaced placeholder secrets: ${result.replaced.join(', ')}`);
    }
    if (result.missing.length > 0) {
      logSuccess(`Generated and appended missing secrets: ${result.missing.join(', ')}`);
    }
    if (!result.wrote) {
      logInfo('All required secrets already configured in .env');
    }

    // Host-OS-aware CHOKIDAR polling (ADS-766). Polling is only useful when
    // Docker bind-mounts cross a host-VM boundary (macOS, Windows). On Linux
    // it burns CPU for nothing — leave the vars unset so docker-compose's
    // ${CHOKIDAR_*:-} interpolation produces empty values.
    const host = platform();
    if (host === 'darwin' || host === 'win32') {
      const envContents = readFileSync(envPath, 'utf8');
      if (!/^\s*CHOKIDAR_USEPOLLING\s*=/m.test(envContents)) {
        appendFileSync(
          envPath,
          [
            '',
            `# ADS-766: ${host} host needs CHOKIDAR polling for Docker HMR.`,
            'CHOKIDAR_USEPOLLING=true',
            'CHOKIDAR_INTERVAL=1000',
            'CHOKIDAR_AWAITWRITEFINISH=2000',
            'WATCHPACK_POLLING=true',
            '',
          ].join('\n'),
        );
        logSuccess(`Appended CHOKIDAR polling vars to .env for ${host} host`);
      } else {
        logInfo('CHOKIDAR polling already configured in .env');
      }
    } else {
      logInfo(`Linux host detected — leaving CHOKIDAR polling disabled (ADS-766)`);
    }
    log('', RESET);

    // Step 3: Install dependencies (pnpm install --frozen-lockfile preserves the lockfile)
    logStep('3', 'Installing dependencies (pnpm install --frozen-lockfile)...');
    logInfo('This may take a few minutes on first run');
    runCommand('pnpm install --frozen-lockfile');
    logSuccess('Dependencies installed');
    log('', RESET);

    // Step 4: Build shared libraries (apps depend on built artifacts)
    logStep('4', 'Building shared libraries...');
    runCommand('pnpm build:libs');
    logSuccess('Libraries built successfully');
    log('', RESET);

    // Step 5: Validate environment configuration
    logStep('5', 'Validating environment configuration...');
    try {
      runCommand('pnpm validate:env');
      logSuccess('Environment configuration valid');
    } catch (err) {
      logError('Environment validation reported issues — review the output above before starting the stack.');
      // Non-fatal: the user may still need to fill in optional values (e.g. third-party API keys).
    }
    log('', RESET);

    // Step 6: Install Playwright browsers (for E2E tests)
    if (skipPlaywright) {
      logStep('6', 'Skipping Playwright browser install (--skip-playwright)');
      logInfo('Run `pnpm test:e2e:install` later if you want to run E2E tests.');
      log('', RESET);
    } else {
      logStep('6', 'Installing Playwright browsers (for E2E tests)...');
      logInfo('This downloads ~200 MB and may take 30–60 seconds.');
      try {
        runCommand('pnpm test:e2e:install');
        logSuccess('Playwright browsers installed');
      } catch {
        logError(
          'Playwright install failed — run `pnpm test:e2e:install` manually before `pnpm test:e2e`.'
        );
        // Non-fatal: a transient network failure shouldn't fail the whole bootstrap.
      }
      log('', RESET);
    }

    // Step 7: Configure git commit message template (idempotent — git config overwrites)
    logStep('7', 'Configuring git commit message template...');
    try {
      execSync('git config commit.template .gitmessage', {
        stdio: 'ignore',
        cwd: ROOT,
      });
      logSuccess('Git commit template set to .gitmessage');
    } catch {
      logError(
        'Failed to set git commit template — run `git config commit.template .gitmessage` manually.'
      );
      // Non-fatal: not every contributor environment has git configured (e.g. some CI sandboxes).
    }
    log('', RESET);

    // Step 8: Offer to enable the opt-in pre-push hook (ADS-797). Catches most
    // CI failures locally by running ci:local:quick before every git push.
    logStep('8', 'Pre-push hook (opt-in)...');
    let enablePrepush;
    if (forceEnablePrepush) {
      enablePrepush = true;
    } else if (forceNoEnablePrepush) {
      enablePrepush = false;
    } else if (!process.stdin.isTTY) {
      // Unattended setup (devcontainer postCreate, CI bots) with no explicit
      // flag: leave the hook disabled rather than silently enabling it.
      enablePrepush = false;
    } else {
      enablePrepush = await promptYesNo(
        'Enable the pre-push hook? Runs ~30s of lint + format + type-check before every git push and catches most CI failures locally. (Recommended for new contributors.)',
        true
      );
    }

    if (enablePrepush) {
      enablePrepushHook();
      logSuccess('Pre-push hook enabled — disable later with `pnpm hooks:disable`.');
    } else {
      logInfo('Pre-push hook left disabled — enable later with `pnpm hooks:enable`.');
    }
    log('', RESET);

    // Success message
    logHeader('Setup Complete! 🎉');

    // Step 9: Offer to start the docker dev stack
    let shouldStart;
    if (forceStart) {
      shouldStart = true;
    } else if (forceNoStart) {
      shouldStart = false;
    } else {
      shouldStart = await promptYesNo('Start the development stack now?', true);
    }

    if (shouldStart) {
      const ok = await startStack();
      if (!ok) {
        printNextSteps();
      }
    } else {
      printNextSteps();
    }

    logSuccess('Happy coding!');
    log('', RESET);
  } catch (error) {
    log('', RESET);
    logHeader('Setup Failed');
    logError(error.message);
    log('', RESET);
    log('Please check the error above and try again.', YELLOW);
    log('For help, see README.md or docs/README.md', YELLOW);
    log('', RESET);
    process.exit(1);
  }
}

await setup();
