#!/usr/bin/env node
import { execSync } from 'child_process';
import { existsSync, copyFileSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomBytes } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const GREEN = '\x1b[32m';
const BLUE = '\x1b[34m';
const YELLOW = '\x1b[33m';

function log(message, color = RESET) {
  console.log(`${color}${message}${RESET}`);
}

function logHeader(message) {
  log('', GREEN);
  log('═'.repeat(60), GREEN);
  log(message, `${GREEN}${BOLD}`);
  log('═'.repeat(60), GREEN);
  log('', GREEN);
}

function logStep(step, message) {
  log(`${BOLD}[${step}]${RESET} ${message}`, BLUE);
}

function logSuccess(message) {
  log(`${GREEN}✓${RESET} ${message}`, GREEN);
}

function logInfo(message) {
  log(`${BLUE}ℹ${RESET} ${message}`, BLUE);
}

function logError(message) {
  log(`${YELLOW}✗${RESET} ${message}`, YELLOW);
}

function runCommand(command, options = {}) {
  try {
    execSync(command, {
      stdio: 'inherit',
      cwd: ROOT,
      ...options,
    });
  } catch (error) {
    throw new Error(`Failed to run: ${command}`);
  }
}

const SECRET_KEYS = [
  'JWT_SECRET',
  'JWT_REFRESH_SECRET',
  'SESSION_SECRET',
  'CSRF_SECRET',
  'ENCRYPTION_KEY',
];

function generateSecret(key) {
  if (key === 'ENCRYPTION_KEY') {
    return randomBytes(32).toString('hex');
  }
  return randomBytes(32).toString('base64');
}

function isPlaceholder(value) {
  if (!value) return true;
  if (/^CHANGE/i.test(value)) return true;
  if (value.includes('your-')) return true;
  if (value.includes('change-me')) return true;
  if (value === 'replace-me') return true;
  return false;
}

function ensureSecretsInEnv(envPath) {
  const contents = readFileSync(envPath, 'utf8');
  const lines = contents.split('\n');

  const replaced = [];
  const missing = [];

  for (const key of SECRET_KEYS) {
    const idx = lines.findIndex(l => l.startsWith(`${key}=`));
    if (idx === -1) {
      missing.push(key);
      continue;
    }
    const existingValue = lines[idx].slice(key.length + 1).trim();
    if (isPlaceholder(existingValue)) {
      lines[idx] = `${key}=${generateSecret(key)}`;
      replaced.push(key);
    }
  }

  if (replaced.length === 0 && missing.length === 0) {
    return { wrote: false, replaced, missing };
  }

  let next = lines.join('\n');
  if (missing.length > 0) {
    if (!next.endsWith('\n')) next += '\n';
    next += `\n# Auto-generated by npm run setup on ${new Date().toISOString()}\n`;
    for (const key of missing) {
      next += `${key}=${generateSecret(key)}\n`;
    }
  }

  writeFileSync(envPath, next);
  return { wrote: true, replaced, missing };
}

async function setup() {
  logHeader("Adopt Don't Shop - Developer Setup");

  try {
    // Step 1: Check Node.js version
    logStep('1', 'Checking Node.js version...');
    let nodeVersion;
    try {
      nodeVersion = execSync('node --version', { encoding: 'utf-8' }).trim();
    } catch {
      logError('Node.js is not installed');
      log('Please install Node.js v20 or higher from https://nodejs.org/', YELLOW);
      process.exit(1);
    }

    const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0], 10);
    if (majorVersion < 20) {
      logError(`Node.js v${majorVersion} detected, but v20+ is required`);
      log(`Current version: ${nodeVersion}`, YELLOW);
      log('Please upgrade Node.js from https://nodejs.org/', YELLOW);
      process.exit(1);
    }

    logSuccess(`Node.js ${nodeVersion} detected`);
    log('', RESET);

    // Step 2: Set up environment configuration BEFORE validation
    logStep('2', 'Setting up environment configuration...');
    const envPath = join(ROOT, '.env');
    const envExamplePath = join(ROOT, '.env.example');

    if (existsSync(envPath)) {
      logInfo('.env file already exists, leaving as-is');
    } else if (existsSync(envExamplePath)) {
      copyFileSync(envExamplePath, envPath);
      logSuccess('.env file created from .env.example');
    } else {
      logError('.env.example not found');
      throw new Error('.env.example is missing from the repository');
    }

    const result = ensureSecretsInEnv(envPath);
    if (result.replaced.length > 0) {
      logSuccess(`Replaced placeholder secrets: ${result.replaced.join(', ')}`);
    }
    if (result.missing.length > 0) {
      logSuccess(`Generated and appended missing secrets: ${result.missing.join(', ')}`);
    }
    if (!result.wrote) {
      logInfo('All required secrets already configured in .env');
    }
    log('', RESET);

    // Step 3: Install dependencies (npm ci preserves the lockfile)
    logStep('3', 'Installing dependencies (npm ci)...');
    logInfo('This may take a few minutes on first run');
    runCommand('npm ci');
    logSuccess('Dependencies installed');
    log('', RESET);

    // Step 4: Build shared libraries (apps depend on built artifacts)
    logStep('4', 'Building shared libraries...');
    runCommand('npm run build:libs');
    logSuccess('Libraries built successfully');
    log('', RESET);

    // Step 5: Validate environment configuration
    logStep('5', 'Validating environment configuration...');
    try {
      runCommand('npm run validate:env');
      logSuccess('Environment configuration valid');
    } catch (err) {
      logError('Environment validation reported issues — review the output above before starting the stack.');
      // Non-fatal: the user may need to fill in non-secret values like POSTGRES_PASSWORD.
    }
    log('', RESET);

    // Success message
    logHeader('Setup Complete! 🎉');
    log('', GREEN);
    log('Next steps:', `${BOLD}${GREEN}`);
    log('', RESET);
    log('1. Review your .env file:', BLUE);
    log('   - Secrets have been generated for you.', RESET);
    log('   - Set POSTGRES_PASSWORD and any third-party API keys you need.', RESET);
    log('', RESET);
    log('2. Start the development stack:', BLUE);
    log('   npm run docker:dev          # recommended (includes database + redis)', RESET);
    log('   npm run dev                 # native (requires local Postgres + Redis)', RESET);
    log('', RESET);
    log('For more information, see:', BLUE);
    log('   README.md                   # Project overview', RESET);
    log('   docs/README.md              # Detailed documentation', RESET);
    log('   .claude/CLAUDE.md           # Development guidelines', RESET);
    log('', GREEN);
    logSuccess('Happy coding!');
    log('', RESET);
  } catch (error) {
    log('', RESET);
    logHeader('Setup Failed');
    logError(error.message);
    log('', RESET);
    log('Please check the error above and try again.', YELLOW);
    log('For help, see README.md or docs/README.md', YELLOW);
    log('', RESET);
    process.exit(1);
  }
}

await setup();
