#!/usr/bin/env node
/**
 * Sitemap generator for app.client (ADS-1327).
 *
 * apps/client/public/sitemap.xml used to be a hand-maintained list of the
 * 5 static top-level routes only — no pet or rescue detail pages, so search
 * engines never discovered the catalogue. This script rebuilds that file
 * with the 5 static URLs PLUS one <url> per publicly-visible pet
 * (`/pets/:id`) and verified rescue (`/rescues/:id`), fetched from the
 * gateway's public listing endpoints:
 *
 *   GET /api/v1/pets     — page-based pagination ({ pagination: { hasNext } }).
 *     Called anonymously and with `status=available` so it only returns the
 *     same catalogue an anonymous visitor can browse (the handler already
 *     hides archived/terminal-status pets from an unauthenticated caller;
 *     the explicit filter just narrows to the pets actually worth indexing).
 *   GET /api/v1/rescues  — cursor-based pagination ({ meta: { hasNext,
 *     nextCursor } }). Called anonymously, which the handler already scopes
 *     to `verified` rescues only (an anonymous caller can't read any other
 *     status) — no explicit status filter needed.
 *
 * Usage:
 *   node scripts/generate-sitemap.mjs [--dry-run]
 *
 * Env vars:
 *   SITEMAP_API_URL   Gateway base URL to read from (default http://localhost:4000)
 *   SITEMAP_SITE_URL  Public site origin the sitemap's <loc> entries use
 *                      (default https://adoptdontshop.app)
 *   SITEMAP_OUT       Output file (default apps/client/public/sitemap.xml)
 *
 * Not wired into CI or the build — the gateway isn't reachable from a CI
 * runner or a static build step. Run it manually (or from a scheduled job
 * with network access to the deployed gateway) whenever the catalogue has
 * grown enough to be worth re-indexing; the 5 static URLs never go stale on
 * their own.
 */
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Sitemap protocol hard cap is 50,000 URLs per file — stay comfortably under
// it for each catalogue rather than reaching for a sitemap index.
const MAX_ENTRIES_PER_KIND = 45_000;
const PAGE_LIMIT = 100;

// --- Pure helpers (unit tested in generate-sitemap.test.mjs) ---------------

/** @param {string} value */
export function xmlEscape(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * @param {string} siteUrl
 * @returns {{ loc: string, changefreq: string, priority: string }[]}
 */
export function staticUrlEntries(siteUrl) {
  return [
    { loc: `${siteUrl}/`, changefreq: 'daily', priority: '1.0' },
    { loc: `${siteUrl}/search`, changefreq: 'daily', priority: '0.9' },
    { loc: `${siteUrl}/discover`, changefreq: 'daily', priority: '0.8' },
    { loc: `${siteUrl}/blog`, changefreq: 'weekly', priority: '0.6' },
    { loc: `${siteUrl}/help`, changefreq: 'monthly', priority: '0.5' },
  ];
}

/** @param {string} siteUrl @param {string} petId */
export function petUrlEntry(siteUrl, petId) {
  return { loc: `${siteUrl}/pets/${petId}`, changefreq: 'weekly', priority: '0.7' };
}

/** @param {string} siteUrl @param {string} rescueId */
export function rescueUrlEntry(siteUrl, rescueId) {
  return { loc: `${siteUrl}/rescues/${rescueId}`, changefreq: 'weekly', priority: '0.6' };
}

/**
 * @param {{ loc: string, changefreq: string, priority: string }[]} entries
 */
export function buildSitemapXml(entries) {
  const urls = entries
    .map(
      ({ loc, changefreq, priority }) =>
        `  <url>\n` +
        `    <loc>${xmlEscape(loc)}</loc>\n` +
        `    <changefreq>${changefreq}</changefreq>\n` +
        `    <priority>${priority}</priority>\n` +
        `  </url>`
    )
    .join('\n');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!--\n` +
    `  Generated by scripts/generate-sitemap.mjs — do not edit by hand.\n` +
    `  Static top-level routes plus every publicly-visible pet and verified\n` +
    `  rescue detail page, fetched from the gateway's public listing endpoints.\n` +
    `-->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
  );
}

// --- Fetching (impure — takes a fetch implementation for testability) -----

/**
 * Pages through GET /api/v1/pets?status=available (page mode) and returns
 * every pet_id.
 * @param {typeof fetch} fetchImpl
 * @param {string} apiUrl
 * @returns {Promise<string[]>}
 */
export async function fetchAllPetIds(fetchImpl, apiUrl) {
  const ids = [];
  let page = 1;
  for (;;) {
    const url = `${apiUrl}/api/v1/pets?status=available&page=${page}&limit=${PAGE_LIMIT}`;
    const res = await fetchImpl(url);
    if (!res.ok) {
      throw new Error(`GET ${url} failed: ${res.status}`);
    }
    const body = await res.json();
    for (const pet of body.data ?? []) {
      if (pet.pet_id) ids.push(pet.pet_id);
    }
    if (!body.pagination?.hasNext || ids.length >= MAX_ENTRIES_PER_KIND) break;
    page += 1;
  }
  return ids.slice(0, MAX_ENTRIES_PER_KIND);
}

/**
 * Cursors through GET /api/v1/rescues (anonymous — scoped to verified
 * rescues by the handler) and returns every rescue_id.
 * @param {typeof fetch} fetchImpl
 * @param {string} apiUrl
 * @returns {Promise<string[]>}
 */
export async function fetchAllRescueIds(fetchImpl, apiUrl) {
  const ids = [];
  let cursor;
  for (;;) {
    const qs = new URLSearchParams({ limit: String(PAGE_LIMIT) });
    if (cursor) qs.set('cursor', cursor);
    const url = `${apiUrl}/api/v1/rescues?${qs.toString()}`;
    const res = await fetchImpl(url);
    if (!res.ok) {
      throw new Error(`GET ${url} failed: ${res.status}`);
    }
    const body = await res.json();
    for (const rescue of body.data ?? []) {
      if (rescue.rescue_id) ids.push(rescue.rescue_id);
    }
    if (!body.meta?.hasNext || !body.meta?.nextCursor || ids.length >= MAX_ENTRIES_PER_KIND) break;
    cursor = body.meta.nextCursor;
  }
  return ids.slice(0, MAX_ENTRIES_PER_KIND);
}

// --- Orchestration ----------------------------------------------------------

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const apiUrl = process.env.SITEMAP_API_URL ?? 'http://localhost:4000';
  const siteUrl = (process.env.SITEMAP_SITE_URL ?? 'https://adoptdontshop.app').replace(/\/$/, '');
  const outPath = process.env.SITEMAP_OUT ?? join(ROOT, 'apps/client/public/sitemap.xml');

  const [petIds, rescueIds] = await Promise.all([
    fetchAllPetIds(fetch, apiUrl),
    fetchAllRescueIds(fetch, apiUrl),
  ]);

  const entries = [
    ...staticUrlEntries(siteUrl),
    ...petIds.map(id => petUrlEntry(siteUrl, id)),
    ...rescueIds.map(id => rescueUrlEntry(siteUrl, id)),
  ];
  const xml = buildSitemapXml(entries);

  console.log(
    `sitemap: ${5} static + ${petIds.length} pet + ${rescueIds.length} rescue = ${entries.length} URLs`
  );

  if (dryRun) {
    console.log('(dry run — not written)');
    return;
  }
  writeFileSync(outPath, xml);
  console.log(`Wrote ${outPath}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error(err);
    process.exit(1);
  });
}
