import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import bcrypt from 'bcrypt';

/**
 * Hash a high-entropy single-use token (verification, reset, invite,
 * unsubscribe, etc.) for storage. SHA-256 is sufficient because the tokens
 * are generated by crypto.randomBytes(32) — 256 bits of entropy makes
 * brute-force infeasible and no slow hash is needed.
 *
 * The raw token only ever lives in the email/URL sent to the user; the DB
 * holds the hash. Verification works by hashing the incoming token and
 * comparing.
 */
export const hashToken = (token: string): string =>
  createHash('sha256').update(token).digest('hex');

const BACKUP_CODE_SALT_ROUNDS = 10;

/**
 * Hash a 2FA backup code. These are short (user-facing) so a slow hash is
 * appropriate — they're effectively passwords that get used once.
 */
export const hashBackupCode = (code: string): Promise<string> =>
  bcrypt.hash(code, BACKUP_CODE_SALT_ROUNDS);

export const verifyBackupCode = (code: string, hash: string): Promise<boolean> =>
  bcrypt.compare(code, hash);

const IV_BYTES = 12;
const TAG_BYTES = 16;
const ENCRYPTION_KEY_HEX_LEN = 64;

const getEncryptionKey = (): Buffer => {
  const raw = process.env.ENCRYPTION_KEY;
  if (!raw || raw.length !== ENCRYPTION_KEY_HEX_LEN) {
    throw new Error(
      `ENCRYPTION_KEY must be set and exactly ${ENCRYPTION_KEY_HEX_LEN} hex chars (32 bytes). ` +
        `Generate one with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"`
    );
  }
  return Buffer.from(raw, 'hex');
};

/**
 * Encrypt a secret that must be round-tripped (e.g. TOTP shared secret).
 * Uses AES-256-GCM: confidentiality + integrity (the auth tag detects
 * tampering). Layout of the returned base64: [12 IV | 16 TAG | N CIPHERTEXT].
 */
export const encryptSecret = (plaintext: string): string => {
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv('aes-256-gcm', getEncryptionKey(), iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, tag, ciphertext]).toString('base64');
};

export const decryptSecret = (encoded: string): string => {
  const buf = Buffer.from(encoded, 'base64');
  const iv = buf.subarray(0, IV_BYTES);
  const tag = buf.subarray(IV_BYTES, IV_BYTES + TAG_BYTES);
  const ciphertext = buf.subarray(IV_BYTES + TAG_BYTES);
  const decipher = createDecipheriv('aes-256-gcm', getEncryptionKey(), iv);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf8');
};
