name: Deploy (Disabled)

# This workflow is disabled until you have deployment infrastructure ready
# To enable: remove the 'if: false' condition and configure the required secrets

on:
  # Commented out to prevent automatic deployment
  # push:
  #   branches:
  #     - main  # Deploy to production
  #     - develop  # Deploy to staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Disabled until deployment infrastructure is ready
    if: false

    steps:
      - name: Deployment Disabled
        run: |
          echo "Deployment is currently disabled."
          echo "To enable deployment:"
          echo "1. Set up a container registry (Docker Hub, AWS ECR, etc.)"
          echo "2. Configure deployment server"
          echo "3. Add required secrets to GitHub repository"
          echo "4. Remove 'if: false' condition from this workflow"
          exit 0
